### ISSUE TITLE
add ability to edit Schedule Set Name from Space Types tab

### ISSUE THREAD

**Issue by MatthewSteen** [openstudiocoalition/OpenStudioApplication#102]
Feature request to add ability to edit `Schedule Set Name` from Space Types tab, which would save users the time of switching back and forth between the Schedule Sets and Space Types tabs to coordinate.

![image](https://user-images.githubusercontent.com/8397034/72295722-5b2b5100-3615-11ea-984b-acd637bef24e.png)

**Comment by jmarrec** [comment]
Just a matter of removing this line: https://github.com/NREL/OpenStudioApplication/blob/61db320fb2e2eda8408e0158ae034f01f5b13c23/src/openstudio_lib/library/OpenStudioPolicy.xml#L1251

And making sure that the name updates correctly.

**Comment by jmarrec** [comment]
Had to open #106 while testing this, I found out that currently you can edit ALL fields in openstudioapplication-1.0.0.
