### ISSUE TITLE
OpenStudioPolicy.xml isn't enforced in openstudioapplication-1.0.0

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#106]
Issue overview
--------------

Found while toying with #102. It seems that the OpenStudioPolicy.xml isn't enforced, I can edit ALL fields of an OS_DefaultConstructionSet on the Space Types tab for example, while I could edit none in 2.9.1

## Current Behavior

**In openstudioapplication-1.0.0**

![image](https://user-images.githubusercontent.com/5479063/81565406-90fcfe00-9399-11ea-908a-f3b29d864d5b.png)

## Expected Behavior

**In openstudio-2.9.1**

![image](https://user-images.githubusercontent.com/5479063/81565376-817db500-9399-11ea-8d51-255d92bb8aca.png)

## Steps to Reproduce

1. Open OpenStudioApplication
2. Go to Space Types tab
3. Drag a space type from library
4. Click on the Default Schedule Set, look the Inspect gadget / Main Right Column Controller.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 18.04
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): openstudioapplication-1.0.0

**Comment by jmarrec** [comment]
OpenStudioPolicy.xml isn't parsed correctly:

https://github.com/NREL/OpenStudioApplication/blob/61db320fb2e2eda8408e0158ae034f01f5b13c23/src/model_editor/AccessPolicyStore.cpp#L350

**Comment by jmarrec** [comment]
Got it, it's because `OS_AirTerminal_SingleDuct_Uncontrolled` was actually removed from the IDD.

```
[AccessParser] <-2> IddObjectType failed conversion:OS_AirTerminal_SingleDuct_Uncontrolled

```

**Comment by eringold** [comment]
That current behavior (in 1.0.0) seems a lot more user-friendly than the expected (2.9.1) behavior. Any chance of keeping it?
