### ISSUE TITLE
OS App v1.0.0 "Measures" tab does not properly render Reporting Measure Arguments

### ISSUE THREAD

**Issue by chrisbalbach** [openstudiocoalition/OpenStudioApplication#108]
Issue overview
--------------
OS App v1.0.0 "Measures" tab does not render Reporting Measure Arguments 

## Current Behavior
While a Reporting measure can be added to a .osm model using the "Measures" tab, NONE of the  measure arguments are rendered in the OS App UI. 

This means OS Reporting measures, if executed as part of a simulation, will only successfully execute if  all 'required' arguments have **defaults** set to **user-desired values**.

Otherwise, there is no way (in the OS App GUI) to change the argument value. 

1) Maneuver to 'Measures' Tab in workflow ribbon
2) Drag and Drop a "Reporting" measure (from BCL or otherwise) that has been authored to contain 'Arguments'.  The "OS Results" measure or "Generic QAQC" measure can be used to demonstrate the bug. While the measure does appear to be added to the model, the measure arguments **are not** rendered in the UI. This means reporting measures, if executed, will only successfully execute if: All 'required' arguments have defaults.  Otherwise, there is no way (in the OS App GUI) to change the argument value. 

## Expected Behavior
The measure, when applied to the model via the drag and drop feature,  should render the arguments in the GUI such that an OS App  user can select from them.

## Steps to Reproduce

1) Open the OS App, beginning with a a 'naked' .osm file 
2) Maneuver to 'Measures' Tab in the workflow ribbon
3) Drag and Drop a "Reporting" measure (from BCL or otherwise) that has been authored to contain 'Arguments' - The "OS Results" measure or "Generic QAQC" measure can be used to demonstrate the bug. 

## Possible Solution
.osm files opened or created in OS Application v2.9.1 does not exhibit this behavior. 
.osm files created in OS Application v2.9.1 then opened in OS Application v1.0.0 do exhibit this behavior.

### Environment
OS Application v1.0.0,  build # 4f5416cfc7, running on Windows 10 OS

### Context
This bug **significantly minimizes overall OS App usability** by making OS Reporting measures only usable via direct CLI based workflows.

**Comment by DavidGoldwasser** [comment]
Seems to be related to this code change here. (Thanks Phylroy!)
https://github.com/NREL/OpenStudio/commit/41388baeae414547260eb5d2fed53b69ce3c2bc7#diff-9940e92849a5870672e98bb83e0cb6fb

When I changed `def arguments` to `def arguments(model)` then the arguments showed up in the GUI. So one fix is to update all the reporting measures, external users would need to do the same (although there are not many external reporting measures, but there are some). Or the application can be updated to be compatible with measures that don't pass in the model.

**Comment by macumber** [comment]
I did this for the ViewModel and ViewData measures, I suggest changing all the reporting measures to:

`def arguments(model = nil)`

That way you support 0-1 arguments

**Comment by macumber** [comment]
https://github.com/macumber/openstudio-vA3C/blob/master/ViewData/measure.rb#L51

**Comment by DavidGoldwasser** [comment]
Thanks @macumber that seems like nice approach.

**Comment by DavidGoldwasser** [comment]
Note, while testing this I confirmed that bool arguments always show as true. There is an existing open issue for that. That issue isn't limited to reporting measures
https://github.com/NREL/OpenStudioApplication/issues/85

**Comment by DavidGoldwasser** [comment]
I can't figure out why, hard to diff XML from BCL vs. GitHub repo, but while arguments show for GitHub copy when brought in through MyMeasures directory, the BCL copy (made from GitHub copy) doesn't work. No idea why at this point. Screenshots are below. I threw away my BCL directory and made a fresh OSM for this test.

For reference test and BCL upload are from this branch ,not develop.
https://github.com/NREL/openstudio-common-measures-gem/tree/bcl_stage_updates

GitHub copy
![Screen Shot 2020-06-25 at 2 12 44 PM](https://user-images.githubusercontent.com/4857055/85792023-06295600-b6f0-11ea-9abb-eff1b4056921.png)

BCL Copy
![Screen Shot 2020-06-25 at 2 16 52 PM](https://user-images.githubusercontent.com/4857055/85792045-0fb2be00-b6f0-11ea-8f38-93e391a1005d.png)

@kflemin and @nllong any thoughts?

**Comment by DavidGoldwasser** [comment]
:( Well this at least explains an error on UH about failed reporting measure with no Output in OSW. Here is bug filed for the Measure, that I can only reproduce with BCL copy of measure, not GitHub repo copy
https://github.com/NREL/openstudio-common-measures-gem/issues/23

**Comment by jmarrec** [comment]
Related PR where I made the change to allow accepting `model` in the `arguments()` method of the reporting measures: https://github.com/NREL/OpenStudio-workflow-gem/pull/94

**Comment by MatthewSteen** [comment]
> 
> I did this for the ViewModel and ViewData measures, I suggest changing all the reporting measures to:
> 
> `def arguments(model = nil)`
> 
> That way you support 0-1 arguments

@macumber's fix worked for me on this measure...

* https://github.com/NREL/openstudio-calibration-gem/tree/develop/lib/measures/TimeseriesObjectiveFunction

**Comment by jmarrec** [comment]
When I did that change:

* The template that ships with the SDK was already updated to be `arguments(model = nil)` https://github.com/NREL/OpenStudio/blob/3650208f2f09905ba612ea122737035bc6577f56/src/utilities/bcl/templates/ReportingMeasure/measure.rb#L27

* A warning is issued in workflow-gem when a reporting measure uses zero arguments: https://github.com/NREL/OpenStudio-workflow-gem/pull/94/files?w=1#diff-6e802bfb7b4e2ae38f326062f77394d6d2b55ff5c6a1c915377602dc1fa0bb06R361

Not sure what else to do there...

**Comment by macumber** [comment]
I think this can be closed
