### ISSUE TITLE
Space Types library item collapses after dragging in Space Type from library

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#116]
Have to keep opening this to drag in more space types

**Comment by jmarrec** [comment]
Still true as of v1.2.0-rc5

**Comment by jmarrec** [comment]
I narrowed it down, this is what triggers it: https://github.com/openstudiocoalition/OpenStudioApplication/blob/7227462c53fd50e9d3e9d9c2209dc0ded90654f6/src/openstudio_lib/ModelObjectListView.cpp#L56-L83

**Comment by jmarrec** [comment]
Can't reproduce on v1.8.0 with Ubuntu 24.04. I suppose this was changed in #713.

@macumber Can you try on windows (or any other platform) to confirm?
