### ISSUE TITLE
Add Exterior Equipment functionality to OS App - Enhancement Request

### ISSUE THREAD

**Issue by eringold** [openstudiocoalition/OpenStudioApplication#126]
Currently (as of v2.5.0) the 'Exterior Equipment' subtab of the Facility tab only enables defining Exterior Lights loads. Other children of ExteriorLoadInstance are not exposed anywhere in the app:

- ExteriorFuelEquipment/ExteriorFuelEquipmentDefinition
- ExteriorWaterEquipment/ExteriorWaterEquipmentDefinition

Either make the existing Exterior Equipment subtab type-generic (with additional columns for specifying type, fuel, etc., or rename to "Exterior Lights" and add subtabs for Loads, Fuel, Water equipment.

**Comment by macumber** [comment]
Related to https://github.com/openstudiocoalition/OpenStudioApplication/issues/393

**Comment by macumber** [comment]
@eringold this build is available for testing if you have any time:

https://github.com/openstudiocoalition/OpenStudioApplication/suites/3210165826/artifacts/74256456
