### ISSUE TITLE
Double click to open does not work on Mac

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#142]
Matt Brown sent a 1.3.0 file.  When double clicking this on a Mac (using 1.4.0) the OpenStudio application launches and initially shows the model.  However, after dismissing the "Model Updated from 1.3.0 to 1.4.0" dialog the app refreshes and an empty model is displayed.  This appears to happen if the model is already up to date as well. 

This does not happen on Windows, it also does not happen on Mac if you go to File->Open.

**Comment by jmarrec** [comment]
OSapp 1.7.0, good enough

![142](https://github.com/user-attachments/assets/594fcddd-a44d-4363-8910-fb8bc8d8f396)
