### ISSUE TITLE
OpenStudioApp Windows crashed during save attempt

### ISSUE THREAD

**Issue by tijcolem** [openstudiocoalition/OpenStudioApplication#177]
A user reported that when using OpenStudioApplication v1.0.0 the application crashes when trying to save the osm. See video at 5:15: https://www.youtube.com/watch?v=swX0ewW325g&t=542s

This very well could be a legitimate permissions problem on Windows when boost is trying to create a directory, but this should be a handled exception vs crash the app. 

This is using Windows: https://github.com/NREL/OpenStudioApplication/releases/download/v1.0.0/OpenStudioApplication-1.0.0.4f5416cfc7-Windows.exe

**Comment by jmarrec** [comment]
Duplicate of #59 that has more info

**Comment by rwadhwa910** [comment]
@tijcolem  I am having the same issue on the newer version of Open studio 3.0.1. I have attached the screenshot.

@DavidGoldwasser

**Comment by rwadhwa910** [comment]
Apart from the crash in the app, When I open the same model again in open studio, I am not able to edit the model in editor tab. The only option I see is of creating a new model.

**Comment by DavidGoldwasser** [comment]
Just to update @rwadhwa910 its comment, the floorplan.json and I believe other files (measures, weather?) have been deleted from the project.

**Comment by rwadhwa910** [comment]
@DavidGoldwasser Weather file was deleted, I am not sure whether measure file was deleted, If that happens again I will note it and update it on this page.

**Comment by DavidGoldwasser** [comment]
Just wanted to share another video demonstrating this by TheEnergyTutor on UH. He appears to not have the directory open, but still gets the crash related to file permission. I could not recreate this on my windows machine following same steps that user did. I had hoped that maybe I could recreate it by deleting a measure in the GUI like he did, but it wasn't reproducible for me.
https://unmethours.com/question/46008/dview-and-severe-crash-help/

**Comment by macumber** [comment]
This appears to still be valid:

https://unmethours.com/question/45931/is-anyone-have-problems-with-floorspace-js-losing-floor-plans/
https://unmethours.com/question/45913/another-unhandled-exception/

**Comment by nklammer** [comment]
I just wanted to add that the trigger for this problem seems to also be having the GitHub Desktop app open during simulation via the OpenStudio App 1.0.1.

**Comment by macumber** [comment]
Was your OSM model directory under version control?  If so GitHub Desktop app was probably locking the files or something like that.  Have you seen this in v1.1.0 or higher?
