### ISSUE TITLE
Upgrade to Qt 5.15 LTS

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#180]
Enhancement Request
--------------
Qt 5.11 is used currently, which isn't a LTS
Qt 5.12 is a LTS, and Qt 5.15 LTS was released in May, might be a good idea to upgrade to Qt 5.15 LTS directly.

https://www.qt.io/blog/qt-5.15-released

**Comment by macumber** [comment]
Would you recommend using Conan for Qt update or do we need to use our own builds?

**Comment by jmarrec** [comment]
conan-qt is such a beast I wouldn't really recommend using it. I'm afraid it'll break every other day, and because we use non-standard recipe options (to get webengine etc), that means you cannot download a binary from bintray and it will build qt, which takes a lot of time, especially in debug (and that takes about 40 GB of disk space in your conan cache).
