### ISSUE TITLE
While Running the simulation on Openstudio 3.0.1 version I am getting this error- ERROR: Input file must have IDF, IMF, or epJSON extension.

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#181]
@tijcolem 

 I am not able to run successful simulation with Open studio version 3.0.1.  I have attached the run.log file along with stdout-energyplus.txt for your reference.

I get the same error when i run simulation on any open studio model on my pc.

We ran the workflow.osw file with command line successfully but when we tried to run the same file using open studio , the same issue encountered again.

[run.log](https://github.com/NREL/OpenStudioApplication/files/4789442/run.log

[stdout-energyplus.txt](https://github.com/NREL/OpenStudioApplication/files/4789445/stdout-energyplus.txt)
)

**Comment by coldwong** [comment]
Have you solve it?

**Comment by jmarrec** [comment]
This should be fixed already I think. If you can reproduce with 1.2.0-rc6 or (1.2.0 if posted already), then please provide files so we can reproduce and I'll reopen. Thanks!
