### ISSUE TITLE
Empty nodes are created whenever I try to drag an equipment from library and that equipment is not supported.

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#188]
Issue overview
--------------
In the image I am trying to place a water heater in the loop and that equipment is not allowed at that location still it creates an empty nodes.

It should not create a node as it is not supported , Although it is not affecting the simulation, but the empty nodes are created everytime i add an equipment that is not supported.
![nodes](https://user-images.githubusercontent.com/63880759/87080090-53bfbb80-c1e4-11ea-9533-f9cd65be0d3b.png)
![Branch'](https://user-images.githubusercontent.com/63880759/87080116-5fab7d80-c1e4-11ea-929a-514eb39d7db6.PNG)

**Comment by jmarrec** [comment]
Please state which Openstudio Application you are using. Also, it seems that you may have corrupted your PlantLoop to begin with.

The WaterHeater (Mixed Or Stratified) should be allowed there.

If you care share a model with the problem I can take a look.

**Comment by rwadhwa910** [comment]
@jmarrec  I am using th 1.0.1 Openstudio App version, I agree with you WaterHeater (Mixed Or Stratified) are allowed, but if I use some other like heat pump it creates a node saying the selected component in this location.

I have uploaded the model in google drive and have shared the link here.

https://drive.google.com/file/d/1ulYK1kknInrZwjOe7FWoGRTPT9YWmwMM/view?usp=sharing

**Comment by jmarrec** [comment]
Just tested and can't reproduce with 1.2.0-rc6. Happy to reopen if detailed steps to reproduce are provided.
