### ISSUE TITLE
Measures tab doesn't show all measures

### ISSUE THREAD

**Issue by MatthewSteen** [openstudiocoalition/OpenStudioApplication#190]
Issue overview
--------------
In v1.0.1 the Measures tab doesn't show all the local measures, wihch is not the case in PAT v3.0.1. This appears to be isolated to specific measure categories. For example, it didn't happen with `Whole Building > Space Types`, but did happen for `Economics`. 

## Current Behavior
![image](https://user-images.githubusercontent.com/8397034/87076419-f70dd200-c1de-11ea-9bc5-48fc5b00bd04.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/8397034/87072596-4d781200-c1d9-11ea-9d01-0a5a34f4dcbf.png)

## Steps to Reproduce

1. Make a copy of a BCL measure from the Measures tab using the `X2` button (`XcelEDATariffSelectionAndModelSetup` shown above).
2. Close the app and reopen

## Possible Solution

The app is copying the original measure's UID instead of creating a new one for the new measure for _some_ measure categories. The app appears to be filtering based on unique UIDs, which is different behavior than PAT. Workaround is to change the copied measure's UID in the XML file.  

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 18.04
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): v1.0.1/3.0.1

**Comment by rwadhwa910** [comment]
@MatthewSteen  I am experiencing the same issue with couple of measures.

Not able to see any measures in space types.

![measure](https://user-images.githubusercontent.com/63880759/87181374-74008080-c29f-11ea-86dc-8e649df914ee.PNG)

**Comment by MatthewSteen** [comment]
@rwadhwa910 that's a separate issue, see #178.

**Comment by jmarrec** [comment]
I think you're hitting #332, something just went wrong because you using "XcelEDATariffSelectionandModelSetup Copy" when copying "XcelEDATariffSelectionandModelSetup". Try to delete your My Measures/XcelEDATariffSelectionandModelSetup Copy and redo with a name that doesn't contain the original name.

I'm closing until further notice.
