### ISSUE TITLE
[Mac] UI is unreadable with white font on grey background

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#203]
Issue overview
--------------

Reported by @ljbrackney : 

>Is it just me, or does the 1.0 App use white on light gray text for pick lists on Mac?  It’s nearly unreadable.
> I thought maybe it was a light/dark mode thing, but it looks crummy no matter which I select.

## Current Behavior

![image](https://user-images.githubusercontent.com/5479063/89418893-f78f7f00-d730-11ea-8a5c-a6049ed5920a.png)

## Expected Behavior

it should be legible!

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Mac
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): openstudioapplication 1.0.0

**Comment by DavidGoldwasser** [comment]
Maybe something unique on @ljbrackney's setup. I'm not seeing that behavior on my computer with 1.0.0 or 1.0.1 app on mac. My mac operating system is 10.15.6
![Screen Shot 2020-08-05 at 10 24 40 AM](https://user-images.githubusercontent.com/4857055/89438594-3fe57780-d706-11ea-8a32-31c2ecc51a6e.png)

**Comment by mbadams5** [comment]
I see it on my Mac with 10.14.6 with OpenStudio 1.0.0
![Screen Shot 2020-08-05 at 1 12 41 PM](https://user-images.githubusercontent.com/2001544/89442938-9a3e0280-d71d-11ea-9db6-3dae099365bb.png)

**Comment by jmarrec** [comment]
Oh boy. That's going to be a fun one :)
Thanks for testing guys.

I guess the coalition is going to need to put their hands on a faulty mac

**Comment by Shoussai** [comment]
I am not having that issue on my Mac, version 10.12.6, on OpenStudio Application 1.0.0
![Screen Shot 2020-08-06 at 5 34 31 PM](https://user-images.githubusercontent.com/33497521/89593255-e8313400-d80b-11ea-895d-24999625650d.png)

**Comment by macumber** [comment]
I just tried this on my Mac, 10.15.6.  I think it is a dark mode issue.  If you set Appearance to Dark mode and restart the OS App you will see this, setting Appearance to Light mode and restarting resolves the issue for me.  I think we would need to figure out how to support dark mode in Qt Applications, seems like it should be possible.

**Comment by jmarrec** [comment]
Pretty sure addressing https://github.com/openstudiocoalition/OpenStudioApplication/issues/180 will fix this one.

It seems that dark mode support may have been added in qt 5.12 only, we use 5.11. https://trac.macports.org/ticket/57574

**Comment by macumber** [comment]
That would be great, upgrading Qt is certainly the first thing we should try.  Should we add upgrading Qt to the 1.1.0 milestone?

**Comment by RKStrand** [comment]
Just ran into this myself while preparing for a class.  Interestingly enough, if I start the app while in light mode but then switch back to dark mode, the text stays visible.  But if I start the app in dark mode, the text is almost unreadable and switching to light mode doesn't help until I have restarted the app.  Not sure if this helps at all, but I thought I'd add my experience here.

**Comment by jmarrec** [comment]
make sure to check out #11 before trying to upgrade Qt

**Comment by MatthewSteen** [comment]
This can also happen on some Linux distributions, e.g. Kubuntu (KDE desktop).

**Comment by rd2** [comment]
On MacOS version 10.15.7 (19H2). Whether I switch from Dark to Light modes before/after (re)starting OsApp, I get the same behaviour:
![OSAPP_Dark_vs_Light_MAC](https://user-images.githubusercontent.com/40636643/95328341-6f823e80-0873-11eb-9f40-12361ea15652.jpg)
In a nutshell, for large areas of the background that are (still) using the OpenStudio default (fixed) mid-range gray color, there doesn't seem to be added value in switching the text from dark to light. If I may take this a step further. Offering OsApp users a Dark Mode option (at least on a Mac) seems to require a fair bit of customization (each tab, each widget). Is this something that needs revisiting each year or so (given the frequency of MacOS updates)? That's food for thought. In addition, for someone like me who uses Dark Mode by default, I'm used to apps that only partially enable the feature (e.g. Office 365), which is fine. Consistency and readability for OsApp users far outweigh desirability for Dark Mode. And this, it seems, remains something of an [ongoing discussion](https://bugreports.qt.io/browse/QTBUG-68850) elsewhere in the AppKit universe (a more recent [example](https://forum.qt.io/topic/114668/dark-mode-in-macos-15-10/2)). In a nutshell, I would suggest (for now) disabling an automated Dark Mode switch for the OsApp until it is deemed satisfactory to a handful of Mac power users. This can be [deactivated](https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app#2993819) for individual apps.

**Comment by macumber** [comment]
Tested on my Mac and it works as intended, thanks for the report @rd2 and for the fix @jmarrec !
