### ISSUE TITLE
Code signing for Windows installer?

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#205]
Issue overview
--------------

I think code signing will be needed to avoid antivirus problems on Windows... Which means we'd need a certificate for signing.

**Comment by jmarrec** [comment]
@marccosta reported getting it with the 1.0.1 installer on a clean windows machine,

![image](https://user-images.githubusercontent.com/5479063/90661068-0a34a880-e247-11ea-828c-7c105c16ff0f.png)

**Comment by macumber** [comment]
Hi @bjorn if you look at https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/.github/workflows/app_build.yml#L524 you can see we are installing the SignPath PowerShell module from https://www.powershellgallery.com/packages/SignPath/2.3.0 and then using that module to do the signing requests.  On the signing policy associated with the certificate we unchecked "Use approval process".  I hope that helps.

BTW: I have used Tiled and think it is a great tool!

**Comment by bjorn** [comment]
@macumber Thanks, I'd like to try this approach, but the release certificate I got from SignPath does not appear to allow disabling the approval process, nor the origin verification. I guess I should be in contact with somebody from SignPath about this.

![image](https://user-images.githubusercontent.com/531764/162609495-37bcfd95-9113-4f63-abe0-335fa04975b9.png)


> BTW: I have used Tiled and think it is a great tool!

Thanks!

**Comment by jmarrec** [comment]
@bjorn are you using an EV (extended verification) certificate (which you must pay for)? That is what we use. I suggest emailing signpath to try and see if they can help
