### ISSUE TITLE
A bug related to OS:Schedule:File and OS:External:File with OpenStudio App

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#213]
Issue is with OpenStudio 

https://github.com/NREL/OpenStudio/issues/4046

**Comment by macumber** [comment]
1. Running a workflow with the measure generates output csvs, output csvs end up in generated files directory, idf files point to schedules in temp directory (fine for simulation)
2. Running measure in apply now generates the csvs, does not properly bring back csvs to generated files or files directory, idf exported has blank file path

**Comment by macumber** [comment]
This is the line that is supposed to make case 2 work: https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/src/openstudio_lib/ApplyMeasureNowDialog.cpp#L128

**Comment by macumber** [comment]
It looks like translate to idf is what is putting the schedule in the correct location during the simulation workflow:

https://github.com/NREL/OpenStudio/blob/4d136973122860b11dcfc976fcaa0268223290d7/src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp#L94

**Comment by macumber** [comment]
We need to repoint new external file objects to files directory in apply measure now.

**Comment by macumber** [comment]
Added example measure to issue files

**Comment by macumber** [comment]
I think I know what the issue is, the CLI is inserting a new path `generated_files` in front of the `WorkingFiles` dir.  We should copy content of `generated_files` back to the `generated_files` in the model dir in addition to the `WorkingFiles` which is getting copied back to the `files` dir

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/issues/4391
