### ISSUE TITLE
DualDuct Thermal Zone Assignment on Splitter Not Working

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#215]
Issue overview
--------------
When selecting the Dual-Duct supply splitter and assigning thermal zones, the thermal zone is not added to the terminal box that was already placed.

## Current Behavior
 See gif
![Emh3UI7afU](https://user-images.githubusercontent.com/69771412/90552017-0b7eac00-e147-11ea-811a-3624bb75a577.gif)

## Expected Behavior
User expects the zone to be assigned to the AirTerminal that has been placed.

## Steps to Reproduce

1. Create a DualDuct system including DualDuct terminal device.  Select supply splitter and a add a thermal zone.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

### Context
 Trying to add multiple thermal zones without manually adding them and the AirTerminals.

**Comment by Ski90Moo** [comment]
Maybe this is not an issue.  It works if you add a thermal zone to the first instance and then select the supply splitter and start adding zones.

**Comment by jmarrec** [comment]
Reproduced in v1.2.0-rc6 on Ubuntu 18.04

**Comment by jmarrec** [comment]
I think the issue is with AirLoopHVAC::terminalForLastBranch which doesn't pick it up

https://github.com/NREL/OpenStudio/blob/92a416c03a98b44b67668e5b3d6d3c89be729afa/src/model/AirLoopHVAC.cpp#L296-L332

Will transfer it over to https://github.com/NREL/OpenStudio/issues/4338
