### ISSUE TITLE
OpenStudioPolicy needed for CoilCoolingDXTwoStageWithHumidityControlMode

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#218]
Issue overview
--------------

At least to hide air inlet/outlet nodes

![image](https://user-images.githubusercontent.com/5479063/90773613-74585680-e2f6-11ea-97f8-54adb596fe49.png)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.0.1

**Comment by jmarrec** [comment]
Hum this may just be that the Policy itself is completely not working. I'll need to check develop.

**Comment by craigers290** [comment]
Thanks. Checked out for me as well.
