### ISSUE TITLE
Crashes when using OpenStudio Results and SI reporting

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#220]
User reports:

https://unmethours.com/question/46477/openstudio-losing-weather-file-and-measures/?comment=46786#post-id-46786

https://unmethours.com/question/46686/using-bcl-openstudio-results-si-measure-causes-simulation-failure/?comment=46690#post-id-46690

**Comment by macumber** [comment]
I think these issues may be resolved with https://github.com/NREL/openstudio-common-measures-gem/issues/33

**Comment by jmarrec** [comment]
This would have to wait for https://github.com/NREL/EnergyPlus/pull/8474

**Comment by jmarrec** [comment]
https://unmethours.com/question/46686/using-bcl-openstudio-results-si-measure-causes-simulation-failure/?comment=46690#post-id-46690 user reported he made a mistake I think.
