### ISSUE TITLE
Extra surfaces made resulting in increase in simulation timing

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#223]
I am making a model and the resulting geometry is having more surfaces, for example in the image below the same space is having more than 1 surface, which is increasing the time required to simulate the model.

Now once the the simulations runs without any error and then you try to open the same project again  excess surfaces and faces are created every time you open the model.

Normally there should not be extra surfaces made for the same space.

I have attached the link to the model.
https://drive.google.com/file/d/1ulYK1kknInrZwjOe7FWoGRTPT9YWmwMM/view?usp=sharing

https://drive.google.com/file/d/1_EUxK7RUD4ey5QoNgS3GDVkkF7lLsyky/view?usp=sharing

Openstudio Application 1.0.1
Windows 10
![FS1](https://user-images.githubusercontent.com/63880759/91098385-9c112c80-e61e-11ea-95d0-4f95a1b5fc46.PNG)

![FS2](https://user-images.githubusercontent.com/63880759/91098393-9f0c1d00-e61e-11ea-8f15-a888cae4d162.PNG)

**Comment by jmarrec** [comment]
This is likely an SDK issue.
