### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#225]
Enhancement Request
--------------
Provide an easy way to switch CI builds between official NREL OS packages and interim packages with changes from the OSC fork .

## Detailed Description
We want to be able to reliably update the version of OS used in the app build, including the ability to use packages with interim changes that are not yet in NREL's official builds.

## Possible Implementation

- Implement github actions for the OSC fork (is there a way to prevent these from being pulled back to NREL?)
- Have OSC fork post packages as GitHub actions artifacts, do not want to post these as releases as that would cause confusion

**Comment by macumber** [comment]
Use case 1: official NREL/OpenStudio package is available with everything OS App needs
- OS App builds against official NREL package, this is preferred

Use case 2: OSC has open PRs to NREL/OpenStudio with changes needed in OS App
- All OSC PRs consolidated on openstudiocoalition/OpenStudio/develop
- Merge openstudiocoalition/OpenStudio/tree/develop into Merge openstudiocoalition/OpenStudio/tree/ci-builder
- Wait for packages to be built, stored as artifacts on GitHub actions
- OS App builds against packages on GitHub actions until NREL package is available

**Comment by macumber** [comment]
I think we should go with Alternative 2 above for now

**Comment by jmarrec** [comment]
I'm working on this.

**Comment by jmarrec** [comment]
Fixed it in #208
