### ISSUE TITLE
Failed to partition Polygon and change in the intersection area after merging the json file with osm

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#228]
Issue overview
--------------
When I try to merge the json file with the current osm file i get this error, Failed to partition polygon , and difference in the initial area and post intersection area.

I have attached the link to the model, also the attached project will create excess faces and surfaces each time you open the project.

https://drive.google.com/file/d/1_EUxK7RUD4ey5QoNgS3GDVkkF7lLsyky/view?usp=sharing

While running the simulation I got a  warning stating that actual area is different from proposed area.

Windows 10,
 OS 3.0.1,
 App 1.0.1.

![fs](https://user-images.githubusercontent.com/63880759/92289380-8842b180-eecd-11ea-8a49-e40e47fc9e3f.PNG)

![fs3](https://user-images.githubusercontent.com/63880759/92289382-8973de80-eecd-11ea-8092-6d793e326665.PNG)

**Comment by jmarrec** [comment]
Assuming this is fixed via https://github.com/NREL/OpenStudio/pull/4221. Try out the v1.2.0-rc6 (or 1.2.0 if it's posted...) and if it still fails, report back and I'll reopen.
