### ISSUE TITLE
3D viewer causing OS to crash

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#233]
See https://github.com/NREL/OpenStudio/issues/4075

**Comment by macumber** [comment]
I am able to replicate this, the translation is very slow and then it crashes.  Update to Qt 5.15 doesn't seem to help.  Will investigate further.

**Comment by macumber** [comment]
Update with latest from https://www.ladybug.tools/spider-2020/spider-idf-viewer/v-2020-10-09/spider-idf-viewer.html and https://nrel.github.io/floorspace.js/

**Comment by macumber** [comment]
This model is blowing up in translation from the model to ThreeJS, see https://github.com/automaticmagic/openstudio-troubleshooting/blob/main/load_floorspace_json.rb for debugging

**Comment by jmarrec** [comment]
Works fine now. Was fixed on the SDK side. I can load the supplied json in under 10 secs:

![image](https://user-images.githubusercontent.com/5479063/120247746-d88c4b80-c274-11eb-98e6-8ca9ed4bf56d.png)
