### ISSUE TITLE
Possible option of a search icon in the output variable tab

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#238]
Enhancement Request
Having a search icon in output variable tab can facilitate the user to search the desired output variable one wants to look for.

In the OS app, one have to manually scroll and look for the output variable he/she wants to select which takes unnecessary time this feature could save a lot of time.

![output](https://user-images.githubusercontent.com/63880759/93530443-d490e700-f8fa-11ea-955f-7fc4e4125d23.PNG)

**Comment by jmarrec** [comment]
@rwadhwa910 this is a good idea. We could have a text box to search by name, as well as a dropdown to filter per IddObjectType (eg display only variables for "OS:Boiler:HotWater").
