### ISSUE TITLE
The image of AirLoopHVAC:OutdoorAirSystem is incorrect

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#249]
Enhancement Request
--------------
The image used for the OutdoorAirSystem shows one of the mixing dampers on the OutdoorAirSystem outlet.  The damper should be depicted inbetween the exhaust outlet and fresh air inlet:
![2020-10-11](https://user-images.githubusercontent.com/69771412/95689784-15adab80-0bc8-11eb-8fbe-5b674f0cee4e.png)

**Comment by jmarrec** [comment]
FYI this is as simple as modifying https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/src/openstudio_lib/images/OAMixer.png (and saving a smaller 24px height one in mini_icons) as well.

**Comment by jmarrec** [comment]
Fixed in #374 

![image](https://user-images.githubusercontent.com/5479063/120304060-b83daa80-c2cf-11eb-80bd-decf093d48e7.png)

**Comment by Ski90Moo** [comment]
Thank you Mr. Marrec.
