### ISSUE TITLE
OpenStudio Application does not find EnergyPlus

### ISSUE THREAD

**Issue by muh182** [openstudiocoalition/OpenStudioApplication#252]
Issue overview
--------------
One of my students has encountered a strange issue when trying to run a working model in the simulation tab. The application is not able to find E+. 

## Current Behavior
Here is the error message in the log file. 
```
[16:16:36.252923 ERROR] :/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/energyplus.rb failed with Unable to find the EnergyPlus executable, :/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/energyplus.rb:55:in `find_energyplus'
:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/energyplus.rb:131:in `call_energyplus'
:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_energyplus.rb:63:in `perform'
:/rub
```

## Expected Behavior
Just run the model

## Steps to Reproduce
I cannot reproduce it on my computers. The model works fine on my computer. 

### Environment
Mac, but does not work on Windows using Parallels

Some images are also as follow: 
<img width="1364" alt="Screen Shot 2020-10-13 at 5 10 01 PM" src="https://user-images.githubusercontent.com/2249257/95918194-fef68880-0d70-11eb-924c-0e84e03d33b4.png">

<img width="219" alt="Screen Shot 2020-10-13 at 5 10 12 PM" src="https://user-images.githubusercontent.com/2249257/95918201-01f17900-0d71-11eb-89bc-bcc5803fef59.png">

**Comment by macumber** [comment]
Can you get us the directory that the model was saved in?  Also the directory that OpenStudio Application is installed in?  Did the student install all components of the OpenStudio Application?

**Comment by muh182** [comment]
Thanks @macumber. Here is the description:

On Mac, the model was saved on Desktop and different versions of OpenStudio are installed in the Applications as follow:

<img width="706" alt="Screen Shot 2020-10-14 at 4 55 27 PM" src="https://user-images.githubusercontent.com/2249257/96060375-f1ff9500-0e55-11eb-8335-5dc6135b9e79.png">

On Windows, OpenStudio is installed on the local C drive and have the same components installed. Here is the installed components:

![unnamed](https://user-images.githubusercontent.com/2249257/96060461-2d01c880-0e56-11eb-9816-a58aa7b56174.png)

**Comment by macumber** [comment]
So the issue occurs when running OpenStudio on Windows using Parallels on a Mac?  The host machine is Mac and OpenStudio is installed on Mac, does the model run when OpenStudio is run on Mac?  Does the error only occur when OpenStudio is running on Windows via Parallels?

**Comment by muh182** [comment]
That's correct. The host is on Mac with Parallels for Windows. 

No, it does not run on any of the platforms. I can try to get more clarifications on this.

**Comment by macumber** [comment]
Any updates @muh182 ?

**Comment by muh182** [comment]
@macumber No, let's close this issue and I will open it if I know more about it.
