### ISSUE TITLE
Application crashes when deleting HVAC loop

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#261]
Issue overview
--------------
The application crashes when the user tries to delete an HVAC air loop.

## Current Behavior
![TlankqSsEG](https://user-images.githubusercontent.com/69771412/97093837-37655480-1604-11eb-9f0d-020561147f6f.gif)

## Expected Behavior
The application should delete the airloop and all associated devices.

This also happens when I try to delete the zone equipment one-by-one.  It deletes all of them except the last, but when I click delete on the last zone, it crashes.  It also crashes when I try to delete the cooling coil.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):  openstudioapplication-1.1.0-rc3

**Comment by jmarrec** [comment]
I think this is a SDK issue, which I have filed on https://github.com/NREL/OpenStudio/issues/4060

**Comment by jmarrec** [comment]
Fixed on sdk side
