### ISSUE TITLE
Zooming in FloorSpaceJS zooms UI in addition to plan space

### ISSUE THREAD

**Issue by DavidGoldwasser** [openstudiocoalition/OpenStudioApplication#264]
Issue overview
--------------
This is new to the 1.1.0. I confirmed with same json file that doesn't happen with 1.0.1. 
## Current Behavior
Here is view when zoomed out
![Screen Shot 2020-10-26 at 10 25 44 AM](https://user-images.githubusercontent.com/4857055/97199879-250b2800-1776-11eb-882c-bc9f5f58ea12.png)

And when zoomed in, notice GUI elements are lost, the entire workspace is zooming and not just the plan area.
![Screen Shot 2020-10-26 at 10 25 54 AM](https://user-images.githubusercontent.com/4857055/97199919-30f6ea00-1776-11eb-9648-d8c6a9b5008b.png)

## Expected Behavior
Zoomed in view should looks like this when zoomed in
![Screen Shot 2020-10-26 at 10 26 10 AM](https://user-images.githubusercontent.com/4857055/97199776-03aa3c00-1776-11eb-9dae-896384f31cb8.png)

### Environment
Tested on Mac.

**Comment by macumber** [comment]
I am not seeing this on Windows

**Comment by macumber** [comment]
I'm also not seeing this on MacOS 10.15.7.  I'm using a Windows style mouse with Natural scroll off.  Do you have some custom scroll settings?  Are you using trackpad or holding down any key when scrolling?

**Comment by DavidGoldwasser** [comment]
@macumber I'm using an external Apple magic trackpad, should behave similar to macbook trackpad. Did a bit more testing
- In OpenStudio Application 1.0.1 I can zoom in and out in two different ways. Two finger scroll up or down (which should be like mouse scroll wheel). I can also use pinch/zoom with two fingers to zoom in and out.
- I did confirm that in OpenStudio Application 1.1.0 the two fingers scrolling up or down does still works as expected. It is only the pinch/zoom that changed behavior with this installer. Know that provides a good work around once someone is aware of this.

**Comment by macumber** [comment]
We updated Qt to 5.15 for 1.1.0, I'm assuming there is some new default behavior for the pinch/zoom.  Do you think there is any benefit to the new pinch/zoom behavior?  Presumably Qt is trying to match what users expect that behavior to do?  Do you think we need to override the new default behavior?

**Comment by DavidGoldwasser** [comment]
Since there is a good work around (using scroll, not pinch) once someone is aware of it, I'd leave it alone for now unless you get a more people confused about it. It only impacts Mac users on a trackpad.
