### ISSUE TITLE
Allow compact schedules editing in the schedules graphical editor

### ISSUE THREAD

**Issue by souliane** [openstudiocoalition/OpenStudioApplication#271]
Enhancement Request
--------------
It would be great to allow viewing/editing the compact schedules in the "Schedules" section.

## Detailed Description

Windows 10 Home
OpenStudioApplication 1.1.0

Compact schedules are sometimes editable in the "Edit" tab of an object (the edition is similar to what we would do in a text editor, without extra help). It would be great if we could also edit them with the OpenStudioApplication graphical schedule editor.

If for any reason this is technically difficult to implement, maybe it is easier to display them in read only mode (I like the graphical editor especially for checking that my schedules are OK, without necessarily editing them).

**Comment by jmarrec** [comment]
* https://github.com/openstudiocoalition/OpenStudioApplication/pull/731
