### ISSUE TITLE
OS:SpaceInfiltration:DesignFlowRate edit panel displays wrong units

### ISSUE THREAD

**Issue by souliane** [openstudiocoalition/OpenStudioApplication#272]
Issue overview
--------------
OS:SpaceInfiltration:DesignFlowRate edit panel displays wrong units for "Flow per Space Floor Area" and "Flow per Exterior Surface Area".

## Current Behavior
The displayed unit for the fields that are mentioned above is m/s.

## Expected Behavior
It should be m3/s-m2 instead.

### Environment
Windows 10 Home
OpenStudioApplication 1.1.0

**Comment by macumber** [comment]
This is a known issue with the OpenStudio units engine.  Basically it simplifies (m^3)/(s*m^2) to m/s.

**Comment by jmarrec** [comment]
Duplicate of https://github.com/openstudiocoalition/OpenStudioApplication/issues/152
