### ISSUE TITLE
"Space Type" filter is unapplied when dropping a "People Definition"

### ISSUE THREAD

**Issue by souliane** [openstudiocoalition/OpenStudioApplication#276]
Issue overview
--------------
"Space Type" filter in "Spaces" / "Loads" section is unapplied when dropping a People Definition.

## Current Behavior
The table is filtered with a "Space Type". Drag and drop a People Definition from the right tab "My Model". The "Space Type" selector still shows the selected space type, but the spaces from all space types are displayed in the table.
If a "Load Type" filter was used, it is still applied though.

## Expected Behavior
"Space Type" filter should still be applied and the table should not show all spaces.

## Steps to Reproduce
This can be reproduced with "seb.osm" that is shipped in "Examples\compact_osw\files".

1. Load seb.osm (it will upgrade to OS 3.1.0)
1. In Space / Loads, filter with both "Space Type" = "Entry way"
2. Drop a "People Definition" from "My Model" the "Entry way 1" space entry.

--> All the spaces are not displayed as the "People Definition" as been added.

### Environment

Windows 10 Home
OpenStudioApplication 1.1.0

**Comment by macumber** [comment]
Fixed with Grid View enhancements
