### ISSUE TITLE
Package Reporting Measure with OS App

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#279]
Enhancement Request
--------------
Package the Reporting Measure with the OS App

## Detailed Description
Including Reporting Measure with OS App will cut down on errors for users with stale or invalid BCL credentials.  It also ensures that we can control the content of the reporting measure for each version of the app.

**Comment by jmarrec** [comment]
This has been done, because of the 3.8.0 non-backward compatible break in OSLibReporting:

* https://github.com/openstudiocoalition/OpenStudioApplication/pull/720
