### ISSUE TITLE
Have a search icon in the right-hand pane.

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#284]
Enhancement Request
--------------

Have a search icon in the right-hand pane.
## Detailed Description

In the OpenStudio Application, one has to manually scroll and look for the model inputs in the right-hand pane he/she wants to select. A search function in the right-hand pane could save a lot of time to search for the desired material and equipment.
![image](https://user-images.githubusercontent.com/52507951/102137821-a6974200-3e18-11eb-838d-bafb4597e42d.png)

**Comment by macumber** [comment]
Good idea

**Comment by jmarrec** [comment]
Fixed via https://github.com/openstudiocoalition/OpenStudioApplication/pull/618
