### ISSUE TITLE
Enable dynamic 3D View

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#285]
Enhancement Request
--------------

Enable dynamic 3D View.
## Detailed Description

The 3D View function in the OpenStudio Application is in one direction. The image can be zoomed in and out but cannot be rotated.

**Comment by macumber** [comment]
You can rotate the 3D model by left click, hold, and moving the mouse.  Does this not work for you?

**Comment by LouYingli** [comment]
Thank you. This method works for me.
