### ISSUE TITLE
Building flashes in the 3D View

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#287]
Issue overview
--------------

When I create building geometry in the OpenStudio Application, then view the building in 3D View, the building flashes.
## Current Behavior

The building image flashes in the 3D View.
## Expected Behavior

The building image should be stable in the 3D View.
## Steps to Reproduce

1. Create building geometry by using the Floorspace JS editor in the Geometry.
2. Click Merge with Current OSM.
3. Click 3D View.
Following is the video link of this bug.
https://drive.google.com/file/d/1APWsp5A32CvrrPDETwJNZKRI2Fe0-NUf/view?usp=sharing

### Environment

 - Platform (Operating system, version): Windows 10 Pro for Workstations
 - Version of OpenStudioApplication: OpenStudio Application 1.0.0

**Comment by macumber** [comment]
That is pretty extreme flashing, have you seen this in OpenStudio Application 1.1.0 (which uses an updated version of Qt and Chromium)?

**Comment by LouYingli** [comment]
The building image can not be seen in the 3D View for OpenStudio Application 1.1.0.

**Comment by macumber** [comment]
Need to try updating version of ThreeJS https://github.com/openstudiocoalition/OpenStudioApplication/issues/233

**Comment by jmarrec** [comment]
@LouYingli Could you try with this installer please? https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc5

**Comment by LouYingli** [comment]
The 3D view of this installer works well.

**Comment by jmarrec** [comment]
@LouYingli Thank you for testing it. Closing!
