### ISSUE TITLE
No rendering color for Foundation surfaces in Geometry Viewer

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#290]
https://github.com/NREL/openstudio-common-measures-gem/issues/53

**Comment by jmarrec** [comment]
Is there anything to do on the app side here @macumber ?

**Comment by macumber** [comment]
We'd want to include this in the embedded viewer when we do https://github.com/openstudiocoalition/OpenStudioApplication/issues/357

**Comment by jmarrec** [comment]
@macumber Now that https://github.com/NREL/OpenStudio/pull/4580 is merged, do we need to do something here?

**Comment by macumber** [comment]
Nope that is all here!  I do want to get all of @antoine-galataud's fixes back into the https://github.com/NREL/openstudio-common-measures-gem/ ViewData and ViewModel measures though.
