### ISSUE TITLE
Provide option to reorder items in the left-hand pane of Geometry/Editor/Floorplan

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#291]
Enhancement Request
--------------
Provide option to reorder items in the left-hand pane of Geometry/Editor/Floorplan.

## Detailed Description
The order of the items in the Geometry/Editor/Floorplan/Space cannot be changed. Putting same spaces neighboring makes edition easier. In the following figure, I want to put Classroom (1), Classroom (2), and Classroom (3) neighboring. But there is no option to reorder these items.
![image](https://user-images.githubusercontent.com/52507951/104225154-3f62b280-5403-11eb-9b82-f8908702af22.png)

**Comment by macumber** [comment]
Would be implemented in FloorspaceJS, added new issue: https://github.com/NREL/floorspace.js/issues/375
