### ISSUE TITLE
Spaces in one story cannot be copied along with this story

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#292]
Issue overview
--------------
In the Geometry/Editor/Story, the spaces in one story cannot be copied along with this story.

## Current Behavior
When I copy a story, the spaces in this story are not copied to the new story.

## Expected Behavior
The spaces in the story should be copied to the new story.

## Steps to Reproduce

1. Click the copy icon in the Geometry/Editor/Story.
Following is the video link of this bug.
https://drive.google.com/file/d/1kenZ33yBQHH9CKeBikcVseJ0jhnCEJe3/view?usp=sharing

### Environment

 - Platform (Operating system, version): Windows 10 Pro (1909) for Workstations
 - Version of OpenStudioApplicatio: OpenStudio Application 1.0.0

**Comment by macumber** [comment]
Would be implemented in FloorspaceJS, existing issue: https://github.com/NREL/floorspace.js/issues/178
