### ISSUE TITLE
Adding Plenum height causes Model running failure

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#294]
Issue overview
--------------
Adding Plenum height causes Model running failure.

## Current Behavior
After adding the Plenum height, the simulation fails to run.

## Expected Behavior
After adding the Plenum height, the simulation should run well.

## Steps to Reproduce

1.	Add Plenum height in the Geometry/Editor/Story.
2.	Click Merge with Current OSM.
3.	Click run.
Following is the video link of this bug.
https://drive.google.com/file/d/1ktQqWDNuxEvNIjGbz2CheoUnfoL3SCvL/view?usp=sharing

### Environment

 - Platform (Operating system, version): Windows 10 Pro (1909) for Workstations
 - Version of OpenStudioApplication: OpenStudio Application 1.0.0

**Comment by macumber** [comment]
Thanks for the report, this seems like a bad issue.

**Comment by macumber** [comment]
I think there are two separate issues here.  

First issue:
1. Create floor plan, merge with model
2. Set building construction set
3. Return to floor plan, merge with model
4. Building construction set is removed

Second issue:
1. Create floor plan, add plenum height, merge with model
2. Assign thermal zone to plenum
3. Return to floor plan, merge with model
4. Additional thermal zones are created
