### ISSUE TITLE
Cannot draw space on geometrical model

### ISSUE THREAD

**Issue by yizhi37** [openstudiocoalition/OpenStudioApplication#295]
Issue overview
--------------
Cannot draw space on geometrical model.

## Current Behavior

After many spaces being created, space cannot be drawn on the current geometrical model.

## Expected Behavior

Space should be shown on the current geometrical model after drawing.

## Steps to Reproduce

1. Click Rectangle to draw the space named Story 4 - Unit D.
2. Draw the space on current model.
3. Create a new space named Space 4 - 1.
4. Click Rectangle to draw the space.
5. Draw the space on current model.
   Following is the video link of this bug.
   https://drive.google.com/file/d/1yacT2xRb5EKcrc-zeiuxZdz4XzqWueB7/view?usp=sharing   

### Environment

- Platform (Operating system, version): Windows 10 Pro for Workstations
- Version of OpenStudioApplication: OpenStudio Application 1.0.0

**Comment by macumber** [comment]
This might be fixed by upgrade to newest FloorspaceJS in version 1.2.0 which includes:

https://github.com/NREL/floorspace.js/commit/8799f0cc7e7cffc7cdb9502507d77ba13d1eef40

Are you able to test with https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc3 ?
