### ISSUE TITLE
Provide batch operations in Geometry/Editor/Floorplan

### ISSUE THREAD

**Issue by yizhi37** [openstudiocoalition/OpenStudioApplication#296]
Enhancement Request
--------------
Provide batch operations in Geometry/Editor/Floorplan.

## Detailed Description
When the building has many spaces of the same type, it is not convenient for users to unify the color by changing it one by one. 
![Picture1](https://user-images.githubusercontent.com/72763751/104261721-2cc49980-5454-11eb-91bb-0ce8b1b9a1fe.png)

**Comment by macumber** [comment]
Moving to https://github.com/NREL/floorspace.js/issues/387
