### ISSUE TITLE
Multiple space types getting created while merging floorspacejs with the OSM file

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#297]
So what is happening when I am trying to Merge the OSM file in the geometry tab multiple space types are getting created, For example in the video that I have attached you can see when the OSM is merged Corridor 3 and Corridor 4 are created . 

https://drive.google.com/file/d/18iau4tVC7tLM_ta54ZMzblk-Ytcfw26T/view?usp=sharing

OS1.1.0
Windows 10

**Comment by macumber** [comment]
That is strange, can you post the OSM and floorplan.json for this model?

**Comment by rwadhwa910** [comment]
@macumber This is the link to the osm file and json.

https://drive.google.com/file/d/18iau4tVC7tLM_ta54ZMzblk-Ytcfw26T/view?usp=sharing

All these three issues 297, 298, and 299 have the same file.

**Comment by macumber** [comment]
@rwadhwa910 it seems that your issue files are no longer on your google drive.  if you are able to repost them i can transfer to our private issue files repo.  sorry i didn't grab them sooner.

**Comment by jmarrec** [comment]
Closing, will reopen if we can reproduce
