### ISSUE TITLE
Multiple Faces and Surfaces getting Created

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#299]
Whenever I run the simulation, It fails and in the process new faces and surfaces gets created and the model fails because new faces and surfaces do not have a construction assign to them as shown in the image below.

I have attached the model I am having issues with.

![1](https://user-images.githubusercontent.com/63880759/104633767-de361b80-565c-11eb-81ca-38d160ab544d.PNG)

OS App 1.1.0
Windows 10

https://drive.google.com/file/d/1KhJf-z2yz15zbxn_hc1x7ugFQv9P7Afb/view?usp=sharing

**Comment by macumber** [comment]
It looks like your default construction set may be missing the entries for interior and exterior wall surfaces.  Have you checked that?

**Comment by macumber** [comment]
I'm pretty sure the issue here is that these spaces don't have space types assigned which would bring in the constructions
