### ISSUE TITLE
Inspector dialog allows setting invalid object names

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#314]
Issue overview
--------------
The InspectorGadget allows setting invalid (e.g. duplicate, empty) names

## Current Behavior
User can setting invalid (e.g. duplicate, empty) names on objects with InspectorGadget in the SketchUp Plug-in, HVAC inspector, etc. OSM files saved in this state are invalid. Object names are "fixed" in non-deterministic way when re-opening the file by `Workspace::resolvePotentialNameConflicts`.  Source of the issue is that `WorkspaceObject::setString` allows these strings to be set.

## Expected Behavior
InspectorGadget should not allow setting invalid object names

## Possible Solution
Revert behavior of `WorkspaceObject_Impl::setString(unsigned index, const std::string& value)` to not allow setting invalid names.

**Comment by jmarrec** [comment]
Fixed via https://github.com/NREL/OpenStudio/pull/4211
