### ISSUE TITLE
Accessing the BCL through the app crashes the app

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#317]
Issue overview
--------------
 When selecting components&measures, find measures or find components, it crashes.

## Current Behavior

![0npuxQYjWn](https://user-images.githubusercontent.com/69771412/109360617-64d53f80-783c-11eb-9f31-0a073a402021.gif)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.1.0 and 1.1.1a3

**Comment by macumber** [comment]
Hmm, I am not able to reproduce this.  Can you try moving your BCL directory (should be at `C:\Users\%userprofile%\BCL`) temporarily?  You can just rename the `BCL` directory to `NotBCL` then start the App.  This should re-prompt you to sign in and start with a clean library.

**Comment by Ski90Moo** [comment]
Ok, that fixed it.  I guess I have to re-download all of my measures and components?
