### ISSUE TITLE
append new ScheduleRule objects rather than inserting to top

### ISSUE THREAD

**Issue by MatthewSteen** [openstudiocoalition/OpenStudioApplication#326]
Enhancement Request
--------------
See https://github.com/openstudiocoalition/OpenStudioApplication/issues/127#issuecomment-474982688. Minor annoyance when adding ScheduleRules sequentially from the beginning of the year to the end.

## Detailed Description

This is what happens to the _first_ `Run Period Profile` after adding another one. 

![image](https://user-images.githubusercontent.com/8397034/112243121-a88c5080-8c12-11eb-8e68-0124443aa556.png)

## Possible Implementation

Change how `Rule Order` is set.

**Comment by macumber** [comment]
I think this is an OpenStudio SDK issue, ScheduleRule's put themselves at index 0 on creation

https://github.com/NREL/OpenStudio/blob/develop/src/model/ScheduleRule.cpp#L596

**Comment by jmarrec** [comment]
Closing, it's an SDK thing. Feel free to open an issue over there.
