### ISSUE TITLE
Make monthly electricity generation from solar cells as an output of simulation results.

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#333]
Enhancement Request
--------------
Make monthly electricity generation from solar cells as an output of simulation results.

## Detailed Description
Monthly electricity consumption data and monthly natural gas consumption data are displayed in the OpenStudio output file. It would be great if the monthly electricity generation from solar cells can also be displayed in the OpenStudio output file.

## Possible Implementation
Monthly electricity generation from solar cells can be used for calibrating the area of solar cells on the rooftop of the building.

**Comment by jmarrec** [comment]
You are refering to the OpenStudio results measure from BCL, which we have absolutely no control over. I suggest opening an issue on https://github.com/NREL/openstudio-common-measures-gem instead, which is where it lives

**Comment by jmarrec** [comment]
Also, there is a section already: https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/openstudio_results/resources/os_lib_reporting.rb#L2453-L2491
