### ISSUE TITLE
Subsurface boundary conditions display wrong 

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#340]
Reported at https://github.com/NREL/OpenStudio/issues/4328

**Comment by macumber** [comment]
@onnomobile Can you let us know what version of the OpenStudio Application you are using?  Are you able to share your OSM that demonstrates the issue?

**Comment by onnomobile** [comment]
Thx. This is a minor bug, but just wanted to let you know. I use OpenStudio Application 1.1.0+b2e7010aa0 (SDK core 3.1.0). Model issued from Sketchup Pro with OS plugin.
![image](https://user-images.githubusercontent.com/84503044/119090361-d4a63100-ba0b-11eb-9795-da363dab7252.png)
I can't upload the osm file apparenty.

**Comment by macumber** [comment]
Nice catch, I've fixed this for 1.2.0
