### ISSUE TITLE
Cannot edit plug load densities on Mac after running simulation and looking at results

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#365]
Issue overview
--------------
Cannot edit plug load densities on Mac

**Comment by macumber** [comment]
Downgrading severity.  This seems to occur when:

1. Run simulation
2. Look at results tab
3. Go directly to Load Definition tab

You can edit the equipment densities but have to hit return rather that just click out of the box, issue seems to resolve after going to other tabs.  My guess is something is wrong with the focus events in this case

**Comment by jmarrec** [comment]
can't reproduce on Ubuntu 20.04

**Comment by jmarrec** [comment]
Can't reproduce on mac M1 with current develop. @macumber retest this yourself if you feel like it and reopen if need be.
