### ISSUE TITLE
Error when opening existing OSM model: Unable to Retrieve OS version 3.1.1 from IddFactory

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#386]
Issue overview
--------------

The app launches fine.  However, when I try to open any of my previous osm models, it gives me this Unhandled Exception:

![2021-06-21](https://user-images.githubusercontent.com/69771412/122791125-cdbe4880-d26d-11eb-963f-e57d893e0ab1.png)

## Current Behavior

The app crashes when I select "Relaunch"

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10 Pro
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.2.0

**Comment by macumber** [comment]
Hmm, it seems that there never was an OS 3.1.1 official release.  Did you happen to make this model with an interim version of the OpenStudio Application?  You might try making a copy of your OSM and try modifying the OS:Version object in the OSM file to be either 3.1.0 or 3.2.0 in a text editor.

**Comment by Ski90Moo** [comment]
Ok, that make sense.  I created the file with the OpenStudio app version 1.1.1.a3.  

In the OSM file, I changed the version to 3.1.0 and I am now able to open it.  Thank you.
