### ISSUE TITLE
A space with a hole cannot be drawn in Floorspace JS

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#392]
Issue overview
--------------
A space with a hole cannot be drawn in Floorspace JS.

## Current Behavior
A space with a hole cannot be drawn in Floorspace JS.

## Expected Behavior
We should be able to draw the space with a hole in Floorspace JS. A space with a hole is a common type of space.

## Steps to Reproduce
Following is the video link of this bug.
https://drive.google.com/file/d/1Huupsx7D-s5Rlw2Dpj2vZCEqlUVBS0KC/view?usp=sharing
### Environment
 - Platform (Operating system, version): Windows 10 Pro (1909) for Workstations
 - Version of OpenStudioApplication: 1.1.0

**Comment by luisclv** [comment]
I feel like this is an EnergyPlus limitation. You normally cannot have a surfaces with holes in the same Space.

**Comment by macumber** [comment]
Agreed
