### ISSUE TITLE
Unable to add Exerior Light Definition

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#393]
Issue overview
--------------
The Facility, Exterior Equipment tab will not allow addition of exterior lights:
![2021-06-30 (1)_LI](https://user-images.githubusercontent.com/69771412/124005140-96e2e380-d98d-11eb-808f-77bca19d1519.jpg)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 
![2021-06-30 (2)](https://user-images.githubusercontent.com/69771412/124005226-ac580d80-d98d-11eb-9ef3-242e76220e15.png)

**Comment by macumber** [comment]
@Ski90Moo would you mind testing that tab in this build?

https://github.com/openstudiocoalition/OpenStudioApplication/suites/3210165826/artifacts/74256456

**Comment by Ski90Moo** [comment]
Yes, it appears to work.  Thank you Dan.
