### ISSUE TITLE
GBXML Import reverses floors/ceilings normals and surface types

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#395]
Enhancement Request
--------------

Currently, when importing a gbxml file from Revit, some of the surface normals get reversed as well as the surface types.  It is very laborious going through and fixing the normals and surface types by hand.

It would be good to have OpenStudio check for and correct this error during the import or have a measure that corrects it after import.

## Detailed Description

This has been reported before and is described in detail here: https://unmethours.com/question/24512/os-imports-gbxml-with-reversed-floor-construction/

**Comment by macumber** [comment]
Moved to OpenStudio issues since gbXML translation is a core SDK feature:

https://github.com/NREL/OpenStudio/issues/4375
