### ISSUE TITLE
Unable to edit Schedule Set name

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#399]
Issue overview
--------------

![2021-07-12_LI](https://user-images.githubusercontent.com/69771412/125341472-7e1ceb00-e308-11eb-966c-323ac44d1992.jpg)
![2021-07-12 (1)](https://user-images.githubusercontent.com/69771412/125341508-84ab6280-e308-11eb-9d3f-e811927b9f71.png)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

**Comment by macumber** [comment]
Nice catch!  This also affected ConstructionSets too, fixed in https://github.com/openstudiocoalition/OpenStudioApplication/pull/398/commits/4d859063247324dab584c7b75c264b96da2cddd8
