### ISSUE TITLE
Geometry preview - search feature

### ISSUE THREAD

**Issue by antoine-galataud** [openstudiocoalition/OpenStudioApplication#404]
Enhancement Request
--------------
Use case: an EnergyPlus simulation is run and there are some errors / warnings about surfaces / thermal zones in `eplusout.err`. It can be useful to quickly show the concerned objects in geometry preview. 

This is more relevant for larger buildings or when no naming convention was applied (ie `Surface 202`, `Surface 203` ...), as it'll often imply long look up times.

**Comment by macumber** [comment]
This looks cool @antoine-galataud, thanks!

I'd also like to apply this as a PR to https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/view_data and https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/view_model and will tag you on that (unless you want to make the pr yourself?)

**Comment by macumber** [comment]
I might also try to make the search function search according to the current render mode and also to highlight all matching surfaces.

**Comment by antoine-galataud** [comment]
@macumber thanks!

> I might also try to make the search function search according to the current render mode

Not sure how well it will render? From a user experience perspective I found keeping only wireframe displayed is visually appealing.

> also to highlight all matching surfaces

Totally makes sense. Please see my latest commit and below example of implementation

![Screenshot from 2021-07-29 10-52-38](https://user-images.githubusercontent.com/5330926/127463316-f8453ec9-c46f-490d-b81b-021e67f0728b.png)

Note: displayed information about matching results will be limited to 2 objects, to avoid overflow in main frame.

**Comment by antoine-galataud** [comment]
@macumber just re-read your last comment and realized I misunderstood. Did you mean searching only among objects having type equal to current render mode? Would make sense indeed

**Comment by antoine-galataud** [comment]
@macumber I implemented search according to current render mode, so it will search only among objects that match render by type.
