### ISSUE TITLE
Geometry preview - air loops

### ISSUE THREAD

**Issue by antoine-galataud** [openstudiocoalition/OpenStudioApplication#413]
Enhancement Request
--------------

The main idea is to implement following use cases in 3D geometry preview:
- find by visual inspection thermal zones that have no air loop associated
- inspect thermal zone / air loop associations to ensure correctness (i.e. AHU dedicated to zones with a specific orientation)  

For now only the first use case can be fulfilled with UI by looking into thermal zones tab in OpenStudioApp and scrolling to find those without an air loop. I often revert back to scripting to perform these checks, but I believe 3D view is a good fit for this too.

## Possible Implementation

Since a thermal zone can be associated with [0..n] air loops, there is a slight difference with other materials implementation:
- air loops information in user data will be of array-like type
- when 'air loop' is selected in 'render by' drop-down, a new drop-down menu could be displayed to select a specific air loop (avoid showing all air loops at once, doesn't make sense if zones are associated with 2 air loops or more).
- this new drop-down menu would have a 'no air loop' entry, to highlight material without any air loop associated.

Dependencies:
- it would require a change in OpenStudio too, mainly in `ThreeJSForwardTranslator` to update user data and ThreeJS materials meta data. A change in `ThreeJS` is also needed to declare the new structures that will hold air loops information.

**Comment by DavidGoldwasser** [comment]
I wonder if most of the work can be in the [ViewModel measure](https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/view_model/measure.rb)? I suppose there may be core changes in `ThreeJS` in OS core as well to support additional data. 

If you wanted to actually edit in geometry editor would need to be in FloorSpaceJS, and then in translators to `ThreeJS` and then to `OSM`. This would get more complex on merging if you go back and change it later once HVAC system is in, so maybe not good idea to squeeze into FloorSpaceJS.

I did have an implementation of [render by air loop in and old light weight SketchUp Plugin Mockup](https://github.com/DavidGoldwasser/osm2su/blob/master/su2osm/su2osmScripts.rb#L37). It is 6 years old and I'm sure doesn't run now without some changes. It stored minimal OS data in SketchUp object attributes.

**Comment by antoine-galataud** [comment]
@DavidGoldwasser thank you for your feedback.

> I wonder if most of the work can be in the ViewModel measure?

Sure. We could do the same as in https://github.com/openstudiocoalition/OpenStudioApplication/issues/404, @macumber took care of porting the enhancement in the relevant measures. I can do it when dev is done too.

It certainly needs a change in a change in  https://github.com/openstudiocoalition/OpenStudioApplication/blob/8a2c08858112355f21b73f75f913603b354078d1/src/openstudio_lib/library/geometry_preview.html, if we want to have this available in the app.

**Comment by macumber** [comment]
@DavidGoldwasser the required changes to OS SDK would just be to export more data (e.g. `AirLoopName`) into the [ThreeUserData](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/geometry/ThreeJS.hpp#L194) when the ThreeJS is exported from OSM [here](https://github.com/NREL/OpenStudio/blob/develop/src/model/ThreeJSForwardTranslator.cpp#L185)

**Comment by antoine-galataud** [comment]
> export more data (e.g. PrimaryAirLoopName)

@macumber I was thinking all air loop names could be returned (vector of strings) to allow searching zones by associated air loop name. You seem to suggest something else.

**Comment by macumber** [comment]
Vector is good 👍
