### ISSUE TITLE
OpenStudio Application v1.2.0 Crashes When Accessing Thermal Zones Tab

### ISSUE THREAD

**Issue by robianson** [openstudiocoalition/OpenStudioApplication#414]
The application crashes whenever I try to navigate to the thermal zones tab. Seems related to this issue: https://gitmemory.com/issue/openstudiocoalition/OpenStudioApplication/378/858855428, although the model I'm using is pretty small (only 45 spaces and thermal zones). The application displays the spaces tab fine, but crashes anytime I navigate to the thermal zones tab. Anyone else had this issue? 

Running production OS App V1.2.0, on Windows 10 Enterprise version 20H2

**Comment by jmarrec** [comment]
@robianson Can you provide your OSM so I can try to reproduce please? (If you rename it `model.osm.txt` you can just drag and drop it on this issue, otherwise a gist or a drive link would work)

Also, would you mind checking with the v1.2.1-rc1 release? https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.1-rc1

**Comment by robianson** [comment]
Thanks, Julien. Here's the model: [Model v120.osm.txt](https://github.com/openstudiocoalition/OpenStudioApplication/files/7020040/Model.v120.osm.txt)

I'll give it a shot with the -rc1 release.

**Comment by robianson** [comment]
FYI - same behavior using the -rc1 release. Application just quits after I click on the thermal zones tab, with no error message.

**Comment by jmarrec** [comment]
in cmd.exe

```bash
cd c:\openstudioapplication-1.2.1-rc1\bin
set OPENSTUDIO_APPLICATION_DEBUG=1
set OPENSTUDIO_APPLICATION_LOGFILE_PATH=%USERPROFILE%\Desktop\osapp.log
.\OpenStudioApp.exe
```

So, here's what the log shows
```
[BOOST_ASSERT] <2> Assertion pl failed on line 2001 of class openstudio::model::PortList __cdecl openstudio::model::detail::ThermalZone_Impl::inletPortList(void) const in file D:\OSN\src\model\ThermalZone.cpp.
```

I have no clue how you managed to break the model, but your ThermalZones are ALL missing some required connections

here's a difference between a valid thermal zone object, and one of your thermal zone objects. Red is yours, green is normal

```
OS:ThermalZone,
  {a9f05572-8ff3-4106-a8fb-21c0d439b1c0}, !- Handle
  Thermal Zone 26,                        !- Name
  ,                                       !- Multiplier
  ,                                       !- Ceiling Height {m}
  ,                                       !- Volume {m3}
  ,                                       !- Floor Area {m2}
  ,                                       !- Zone Inside Convection Algorithm
  ,                                       !- Zone Outside Convection Algorithm
  ,                                       !- Zone Conditioning Equipment List Name
-  ,                                       !- Zone Air Inlet Port List
+  {07c0de42-9c2f-4746-865b-cb0d91c47e7d}, !- Zone Air Inlet Port List
-  ,                                       !- Zone Air Exhaust Port List
+  {749ae76d-879c-4588-9a59-a01b78290fc5}, !- Zone Air Exhaust Port List
  {e064d139-61a1-435e-a2d9-02d87e1b6eb9}, !- Zone Air Node Name
-  ,                                       !- Zone Return Air Port List
+  {2e45fcb2-53f4-44ff-8240-4c5cc4446dc6}, !- Zone Return Air Port List
  ,                                       !- Primary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Primary Daylighting Control
  ,                                       !- Secondary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Secondary Daylighting Control
  ,                                       !- Illuminance Map Name
  ,                                       !- Group Rendering Name
  ,                                       !- Thermostat Name
  No;                                     !- Use Ideal Air Loads
```

**Comment by jmarrec** [comment]
I'm closing this issue as this is really an issue with your model that the SDK isn't happy with. So this isn't something the App should be concerned with.

I'm happy to keep helping if I can though, so feel free to write here. Also, I'm curious what you've done that may have broken your model that badly?

**Comment by robianson** [comment]
Thanks a lot for the debugging, Julien. The model I sent was built using the Sketchup plugin v1.2.0 in Sketchup Pro 2021, and the zones were created with the "Add New Thermal Zone for Spaces with No Thermal Zone" user script, with no editing directly in the text file. Very strange. Reinstalled the plugin and rebuilt the model and the zones appear to have all of their ports defined.
