### ISSUE TITLE
Allow access to AdditionalProperties

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#417]
Enhancement Request
--------------
Allow users to set AdditionalProperties for objects

## Detailed Description
AdditionalProperties are used for adding data to objects that can be used in downstream measures.  Currently there is no way to see these properties in the UI

## Possible Implementation
Allow users to set AdditionalProperties for object in the InspectorGadget so it can be used in OpenStudio Application and SketchUp Plug-in

**Comment by jmarrec** [comment]
Fixed via #715
