### ISSUE TITLE
Consider linking to FloorSpaceJS instead of embedding

### ISSUE THREAD

**Issue by DavidGoldwasser** [openstudiocoalition/OpenStudioApplication#42]
Currently a static copy of FloorSpaceJS is embedded in the OpenStudio Application, but I propose linking to the live development version instead.
https://github.com/NREL/floorspace.js

I see three advantages to this approach.
1. it makes the source code smaller
2. It makes maintaining the application easier, related to updates to FloorSpaceJS
3. It gets updates to the application as soon as they go live in FloorSpaceJS

The downside is that it requires you to be online to use, but some elements of FloorSpaceJS, specifically the map overlay, already require internet access. For reference the graphs in the OpenStudio Results measure only render when you are online. I have not gotten any negative feedback about that.

This could still be visually embedded within the application with the same kind of file management. I can understand how it would not be appealing to jump back and forth between the OS App and an external web browser.

@kbenne @asparke2 @jmarrec any thoughts on this either way?

**Comment by jmarrec** [comment]
Not pursing this. And I don't want to risk the app breaking if something upstream changes, now that two separate organizations maintain the OS App and floorspace.
