### ISSUE TITLE
Material gets duplicated when dragging it just a bit on the Construction tab

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#422]
Issue overview
--------------

Reported by @eringold on #415 

Select a material already in a construction and drag to layer drop zone -> it will be copied. After, select a material and drag _just a tiny bit_, and it will be added again. 

## Current Behavior

![1 2 1rc_cons](https://user-images.githubusercontent.com/10799524/130646606-65629843-3e3d-4087-84e8-fa15694b3df8.gif)
3. #420

## Steps to Reproduce

See gif above

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows at least, not Ubuntu
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.2.1-rc1

**Comment by jmarrec** [comment]
I **cannot** reproduce the issue on **Ubuntu 18.04** with either OpenStudio 2.9.1, openstudioapplication 1.1.0, 1.2.0 or 1.2.1-rc1

**Comment by macumber** [comment]
I am able to reproduce this.  It only seems to occur after you have dragged a material from the construction onto the drop zone.  After that the behavior starts.  My thought is to disallow dragging materials from the construction to the drop zone completely.  Is that an ok fix?

**Comment by macumber** [comment]
I also see a crash if you open the app, navigate to the constructions tab, then hit the plus button without selecting an object type.

**Comment by macumber** [comment]
This is the source of the bug https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/src/openstudio_lib/ConstructionObjectVectorController.cpp#L172

**Comment by macumber** [comment]
@eringold I believe I have a fix for this on https://github.com/openstudiocoalition/OpenStudioApplication/pull/425, would you be able to test it out in this installer: https://github.com/openstudiocoalition/OpenStudioApplication/suites/3624924372/artifacts/87684947

**Comment by eringold** [comment]
@macumber I see the issue resolved with that fix - no additional materials get added with slight movement of the existing material.

I did notice that you can swap a material with the one 'above' it in the construction list by dragging it to the above position, but this is not reversed: to swap positions with the one below, you must drag it to the second position below. And you cannot move a material to the last position - you either have to add it to the bottom drop zone and delete the original, or shift up all the below materials. This seems clunky and weird:
![mat_pos](https://user-images.githubusercontent.com/10799524/131267900-aaa142d2-2e68-4c75-a33f-66caf156a507.gif)

Thanks as always for your efforts!

**Comment by macumber** [comment]
Currently if you drag an existing material A onto existing material B, material A is moved to right in front of B.  

We could change it so material A was moved after material B if material A was before B initially.  However, I think it might not be obvious to the user and it would be confusing if sometimes A came before B and sometimes it came after. 

We could also make it so if you dragged an existing material A onto the "Drag From Library" drop zone that material was moved to the end instead of duplicated.  If you wanted to drag it in to make a new duplicate layer you would have to drag it from the "My Model" library.  What do you think about that @eringold ?

**Comment by macumber** [comment]
@eringold can you try the new behavior in https://github.com/openstudiocoalition/OpenStudioApplication/suites/3626624079/artifacts/87743740 ?  Do you like it better?
