### ISSUE TITLE
SubSurface types don't line up with many subsurfaces in space

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#477]
Issue overview
--------------
With many subsurfaces in a space, the subsurface types don't line up well

![image](https://user-images.githubusercontent.com/1327850/146652546-3399f675-490c-44dd-9e5a-a084e5d6b678.png)

This makes it hard to edit subsurfaces

## Steps to Reproduce
See OSM in issue files repo

**Comment by macumber** [comment]
Seems to happen with small numbers of subsurfaces too

**Comment by jmarrec** [comment]
Example model has this issue already. Current develop, mac M1

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/5479063/166530248-2bfb541b-6d01-40bc-8245-406c5d77d483.png">

**Comment by macumber** [comment]
Confirmed this is fixed
