### ISSUE TITLE
Measure updates on BCL don't work

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#479]
Issue overview
--------------
Download a measure from BCL, update measure on BCL, app detects new version is available but won't download it.

## Current Behavior
App detects new version is available but won't download it.
![image](https://user-images.githubusercontent.com/1327850/147901527-53696353-b601-4b1b-b1f2-5dfe9d283fda.png)

## Expected Behavior
App should show check box next to measures with update and allow user to download them.

**Comment by jmarrec** [comment]
App doesn't actually detect there's a new version at all. It shows that checkbox as checked (by not checkable) because you already have it.
