### ISSUE TITLE
compiling current version on ubuntu 20.04

### ISSUE THREAD

**Issue by dubois34** [openstudiocoalition/OpenStudioApplication#480]
Hi there,
Few months ago I succeeded in compiling OpenStudioApplication on my ubuntu laptop.
I tried to do an update and now it fails.

In a new build folder I did
aqt install --outputdir ./Qt-install 5.15.0 linux desktop gcc_64 -m qtwebengine qtwebglplugin
cmake .. -DCMAKE_BUILD_TYPE=Release -DQT_INSTALL_DIR=./Qt-install/5.15.0/gcc_64/

cmake did a lot of things, but it failed on 

-- Conan executing: /home/dubois/.my_venvs/py385-nrj/bin/conan install . -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing -o=zlib:minizip=True
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
zlib:minizip=True
[build_requires]
[env]

openstudio_ruby/2.7.2@nrel/testing: Retrieving from predefined remote 'nrel'
openstudio_ruby/2.7.2@nrel/testing: Trying with 'nrel'...
ERROR: HTTPSConnectionPool(host='conan.commercialbuildings.dev', port=443): Max retries exceeded with url: /artifactory/api/conan/openstudio/v1/ping (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Unable to connect to nrel=https://conan.commercialbuildings.dev/artifactory/api/conan/openstudio
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
CMake Error at build/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:759 (old_conan_cmake_install)
  ConanInstall.cmake:75 (conan_cmake_run)
  CMakeLists.txt:62 (include)

-- Configuring incomplete, errors occurred!
See also "/home/dubois/WORK/CODES/OpenStudioApplication/OpenStudioApplication/build/CMakeFiles/CMakeOutput.log".

Having a look to https://conan.commercialbuildings.dev it seems that openstudio is available here : https://conan.commercialbuildings.dev/artifactory/openstudio/ 
and not here
https://conan.commercialbuildings.dev/artifactory/api/conan/openstudio

Does it means that the file ConanInstall.cmake has to be modified ?

Thanks for your help.

Regards

**Comment by macumber** [comment]
I think the URLs in `ConanInstall.cmake` are likely correct given that they are working on CI.  My guess is that something is off with your local environment.  What version of conan are you using (`conan -v`)?  I have 1.41.0, the CI is using 1.43.0, I remember some issue with earlier versions.  Can you try `pip3 install conan --upgrade` and see if that fixes the issue?  You could also try clearing your conan cache `conan remove "*" -s -b -f`

**Comment by dubois34** [comment]
Hi,
I did an update of conan (mine is 1.44 now) and I cleared the cache.
When I cleared the cache it said:
%<---
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /home/dubois/.conan/settings.yml.new
WARN: ****************************************
Removing the 'cacert.pem' file...
%<---
Since it was a connection problem I suspect that removing the cacert.pem file solved the problem. 

Anyway, now it compiles.

Thanks
