### ISSUE TITLE
Openstudio Result measure tab not reporting Interior lighting summary

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#486]
Running Openstudio Results measure does not report Interior Light Summary.

![image](https://user-images.githubusercontent.com/63880759/153064874-939c0b00-24a0-4169-bbfa-97ea76bb18b4.png)

**Comment by manuvarkey** [comment]
I think this is due to some zones not being assigned to a thermal zone. Found the following discussion.

https://unmethours.com/question/45911/interior-lighting-summary-open-studio/

**Comment by jmarrec** [comment]
In any case, this isn't a problem of ours. The measure lives on this repo: https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/openstudio_results
