### ISSUE TITLE
Enable 'x2' button to clone Plant Loops in HVAC Systems tab

### ISSUE THREAD

**Issue by eringold** [openstudiocoalition/OpenStudioApplication#487]
Enhancement Request
--------------
@jmarrec [gave us](https://github.com/NREL/OpenStudio/pull/3238) a working PlantLoop::clone method, but as far as I can tell it's not implemented in OSApp - clicking the 'x2' icon when viewing a plant loop in the HVAC Systems tab does nothing.

(v1.3.0+5faa91ea6b)

**Comment by jmarrec** [comment]
@eringold it's a very easy change, https://github.com/openstudiocoalition/OpenStudioApplication/blob/202dfeecb4eed44902384d1d33cb92f1b753747d/src/openstudio_lib/HVACSystemsController.cpp#L869-L879

A great first issue, wanna give it a shot 😉?

**Comment by jmarrec** [comment]
Note you don't even need to check if it's an airloophvac anymore. If loop: loop->clone() is enough
