### ISSUE TITLE
Update Conan CMAKE

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#489]
Enhancement Request
--------------
Implement suggested Conan CMake commands to download all CMAKE_CONFIGURATION_TYPES

## Detailed Description
Doing this will allow RelWithDebInfo builds on Windows

## Possible Implementation
See https://github.com/conan-io/cmake-conan#using-conan_cmake_autodetect-and-conan_cmake_install-with-multi-configuration-generators

**Comment by jmarrec** [comment]
this is done on develop now
