### ISSUE TITLE
Add field DesignHeatRecoveryWaterFlowRate to the ChillerElectricEIR object

### ISSUE THREAD

**Issue by mdahlhausen** [openstudiocoalition/OpenStudioApplication#501]
Enhancement Request
--------------
ChillerElectricEIR supports modeling heat recovery chillers with a split condenser by setting the DesignHeatRecoveryWaterFlowRate field.  This is available in OpenStudio but it is not yet available in the application.  Once set, the user can drag and drop a chiller in the model into the demand side of a heat recovery loop to provide heating to that loop.  Only works with water-cooled chillers.

**Comment by jmarrec** [comment]
@j-lorrey This just requires changing the OpenStudioPolicy.xml: https://github.com/openstudiocoalition/OpenStudioApplication/blob/6a7ef37778e3a4ebb1891d522375f7bf69dec558/src/openstudio_lib/library/OpenStudioPolicy.xml#L588
