### ISSUE TITLE
Compile for Mac M1 architecture

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#505]
Enhancement Request
--------------
Compile for Mac M1 architecture

**Comment by macumber** [comment]
Added CI as a separate story: https://github.com/openstudiocoalition/OpenStudioApplication/issues/506

**Comment by jmarrec** [comment]
Done, 1.4.0-rc1 has an M1 installer that seem to work (on machines that aren't my own where I built it)
