### ISSUE TITLE
Update OSM libraries to SDK 3.4.0

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#508]
Enhancement Request
--------------
Update OSM libraries to SDK 3.4.0

**Comment by jmarrec** [comment]
Once 3.4.0 official is released, use the CLI to run this script:

https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/developer/ruby/UpdateOSMVersions.rb

Then commit the results.

**Comment by jmarrec** [comment]
(I went ahead and did it since I just updated everything to 3.4.0 anyways. I wish I had remembered before I sent 1.4.0-rc1 to build)
