### ISSUE TITLE
Fix TGZ installer on Mac

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#512]
Enhancement Request
--------------
Symlinks are created in the [OpenStudioApplication/src/openstudio_app/install_operations.qs](https://github.com/openstudiocoalition/OpenStudioApplication/blob/7078341fc4628ae5746c093c898fb97901d00b6a/src/openstudio_app/install_operations.qs#L32-L34)

We should cmake install that symlink instead of having it in the install_operations.qs so that the tar.gz installer works too.

See https://github.com/openstudiocoalition/OpenStudioApplication/pull/499

**Comment by jmarrec** [comment]
What would be great is also to have a functional OpenStudioApp inside the build folder. Currently I have to build a package everytime I want to test something, and that's annoying.

**Comment by jmarrec** [comment]
I think this works now.

https://github.com/openstudiocoalition/OpenStudioApplication/blob/bcae7d2dfb684f8d81882c632d48e27945b62bd5/src/openstudio_app/CMakeLists.txt#L446-L452

**Comment by jmarrec** [comment]
https://github.com/openstudiocoalition/OpenStudioApplication/commit/9b44ca2c86ef27757fad294e3c968b51f573ed72
