### ISSUE TITLE
Too many new lines in Verbose output on the Run tab on Windows

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#522]
Issue overview
--------------

## Current Behavior

![image](https://user-images.githubusercontent.com/5479063/167115556-afce107d-8882-403c-8975-ce2238bd2af7.png)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows only
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.4.0-rc1

### Context

cf #519

**Comment by macumber** [comment]
Verified fix, nice job!
