### ISSUE TITLE
Measures list is not updated after download from BCL

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#523]
Issue overview
--------------

## Current Behavior

After downloading a measure from the BCL, I had to switch tabs and go back to the "Measures" tab to see it in the "Library"

## Expected Behavior

It should be updated

## Steps to Reproduce

1. Go "Measures" tab
2. Click "Find Measures"
3. Download a measure, for eg "set window to wall ratio". Close dialog
4. Measures list is not updated, there are zero measures under Envelope > Fenestration.
5. Switch to another tab and come back: this time the measure is there

## Possible Solution

It may be due to changes in #517 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

### Context

cf #519

**Comment by macumber** [comment]
We probably need to test the case of downloading a measure from BCL, updating on BCL, downloading an update in the app so more.  I had an old OpenStudio Results measure and it did not seem to be updating correctly to the new one.  Solution was to delete the BCL measures dir and re-download (not great)

**Comment by macumber** [comment]
Probably also need a "Downloading" dialog while downloading updates

**Comment by macumber** [comment]
I think this issue is more serious. I had an old version of OpenStudio Results Measure in my BCL dir and in my current model.  The new feature found and downloaded the new version of the measure to my BCL dir.  However, after that, the Synch Project Measures with Library button did not detect an updated measure and update the model, even after restarting the OS App.

**Comment by macumber** [comment]
And now after clicking around a bit more it did finally detect the update....
