### ISSUE TITLE
Segfault when action (example model / language preferences) tries to restart the app

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#524]
Issue overview
--------------

## Current Behavior

When doing an action that tries to destroy the app and relaunch - Load Example Model or change Language preferences - the App will often segfault.

## Expected Behavior

No one likes segfaults

## Steps to Reproduce

1. Launch App
2. Click "Examples" > "Example Model" or Change language preference, it'll try to restart the app
3. It'll segfault like 50% of the time or so.

## Possible Solution

Either figure out the root cause (in qt), or work around it:
* Language pref: just tell the user to restart the app manually
* Example Model: Ask use for a filepath via a dialogbox, then start a QProcess to the cli: `openstudio -e "m = OpenStudio::Model::Model.new; m.save(m, "{USER_PATH}")'`

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): v1.4.0-rc1#519 

# Context:

cf #519

**Comment by macumber** [comment]
I hit this too, got a couple of random crashes too.  I turned on the debug logging

**Comment by jmarrec** [comment]
Fixed via #539
