### ISSUE TITLE
WaitDialog can have black background under text

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#530]
Issue overview
--------------

![image](https://user-images.githubusercontent.com/1327850/167315335-92bb8dbf-d5cf-47fa-ac3c-e12ff6f2b832.png)

### Environment

Some additional details about your environment for this issue (if relevant):
64-bit operating system, x64-based processor
Windows 10 Pro

**Comment by macumber** [comment]
The `OSDialog::paintEvent` also results in weird looking horizontal pattern on the window bar

**Comment by jmarrec** [comment]
@macumber you touched WaitDialog in #539 (specifically in https://github.com/openstudiocoalition/OpenStudioApplication/commit/388ea1cf55719478410ddb8a9f7a33580b645baf) , could you try to reproduce the issue and see if it fixes it please?

**Comment by macumber** [comment]
Yup, this is resolved
