### ISSUE TITLE
Offset drop downs for measure arguments on the measure tab

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#535]
Issue overview
--------------
Using a measure with drop down arguments, selecting the drop-down results in the choice list showing offset

## Current Behavior
![image](https://user-images.githubusercontent.com/1327850/167756113-cada223c-6e9e-4cd8-aebd-bf50876126ed.png)

## Expected Behavior
Drop down choices should appear related to the argument box
### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): v1.4.0-rc1

### Context
Confusing

**Comment by jmarrec** [comment]
Windows:

![image](https://user-images.githubusercontent.com/5479063/172339798-b1eb2bf0-1d85-49a9-9cc4-c51f537afe79.png)

**Comment by jmarrec** [comment]
Having a real hard time to determine what's going on. I removed all styling applied in the two qss files to QComboBox, QListView, QAbstractItemView, QFrame and IGRow. Still having the issue. I also tried to make a MCVE outside of openstudioapp but couldn't reproduce the issue.

https://github.com/openstudiocoalition/OpenStudioApplication/blob/f3d7afb29064b40d75ac8c3c7ec6ca02d48b18b3/src/model_editor/InspectorDialog.qss#L1-L26

https://github.com/openstudiocoalition/OpenStudioApplication/blob/f3d7afb29064b40d75ac8c3c7ec6ca02d48b18b3/src/openstudio_lib/openstudiolib.qss#L1-L26

https://github.com/openstudiocoalition/OpenStudioApplication/blob/f3d7afb29064b40d75ac8c3c7ec6ca02d48b18b3/src/openstudio_lib/openstudiolib.qss#L101-L166

https://github.com/openstudiocoalition/OpenStudioApplication/blob/f3d7afb29064b40d75ac8c3c7ec6ca02d48b18b3/src/openstudio_lib/openstudiolib.qss#L180-L192

https://github.com/openstudiocoalition/OpenStudioApplication/blob/f3d7afb29064b40d75ac8c3c7ec6ca02d48b18b3/src/openstudio_lib/openstudiolib.qss#L252-L254

etc

**Comment by macumber** [comment]
Current develop:

Resolution 1920x1080 (Recommended), Scale 100% 
![image](https://user-images.githubusercontent.com/1327850/172524860-75604a97-3f4f-4cb9-8b8c-74226805f973.png)

**Comment by macumber** [comment]
@jmarrec the images above show what current develop and 1.4.0-RC1 look like on my laptop.  I am probably using old person settings 1920x1080, Scale 125% but that is what Windows recommends as the default.

**Comment by macumber** [comment]
My suggestion is to leave this as is for now and I can try to get this looking a little better on https://github.com/openstudiocoalition/OpenStudioApplication/pull/540 for a 1.4.1.  What do you think?

**Comment by macumber** [comment]
Drop downs look good for me on current develop btw, no offset
