### ISSUE TITLE
Text too large on OSItems

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#536]
Enhancement Request
--------------
The text on OSItems seems larger than it used to be

## Detailed Description
Comparison of 1.4.0 vs 1.3.0

![image](https://user-images.githubusercontent.com/1327850/167758471-6ecee4ea-9151-4308-81ba-9a4613b309f2.png)

## Possible Implementation
Adjust stylesheet for OSItem

**Comment by macumber** [comment]
Overall changes in Qt 6 seem like they are making better use of UI real estate

**Comment by jmarrec** [comment]
The biggest issue here is that on 1.4.0 there's an extra "Airplane mode off" overlay that we didn't have in 1.3.0 :)

**Comment by macumber** [comment]
The tab icons are a bit blurry on my resolution after https://github.com/openstudiocoalition/OpenStudioApplication/issues/535

@jmarrec I don't see the "Airplane mode off" overlay, is that an Ubuntu thing?

**Comment by jmarrec** [comment]
The overlay mention was a joke, it's in your screenshot but I know that's windows/your laptop and not the osapp

![Screenshot_20220609-004516_Firefox.jpg](https://user-images.githubusercontent.com/5479063/172729997-c016cf2b-5b47-4b56-b5ca-3a759be06ef6.jpg)

We can look into the icons being blurry, but I'd rather have them a bit blurry than have 2 drop-downs out of 3 being out of place.

**Comment by jmarrec** [comment]
As a reminder from #540, the move might be helpful to investigate this without the overhead of building and running a large project. And the Qt ticket we should monitor

> See this MCVE: https://github.com/jmarrec/QtTestbed/tree/main/Test-Combobox-Popup-Issue

> And the bug report I filed at Qt's issue tracker: https://bugreports.qt.io/browse/QTBUG-104073
