### ISSUE TITLE
EPW Line 5 Syntax - HOLIDAYS/DAYLIGHT SAVING

### ISSUE THREAD

**Issue by akrickx** [openstudiocoalition/OpenStudioApplication#546]
Issue overview
--------------
OpenStudio is requesting an EPW syntax (and fails to load an EPW file) that is not required when using EP-Launch.

## Current Behavior
OpenStudio fails to load an EPW file with the following line 5 syntax:
HOLIDAYS/DAYLIGHT SAVING, 

They load fine in EP-Launch but do not load when opened within OpenStudio. The syntax that OS requires is:
HOLIDAYS/DAYLIGHT SAVINGS, (an extra 'S' at the end)

## Expected Behavior
OpenStudio should be able to load the weather file.

## Steps to Reproduce
Use a weather file with the above syntax (my files came from https://www.csiro.au/en/research/environmental-impacts/climate-change/state-of-the-climate/previous/state-of-the-climate-2018/future-climate)
Attempt to Open an EPW with this syntax
EPW file will fail to load.

In EP-Launch, you can load + simulate the same EPW file without error. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Windows 10 Pro:
 - Version of OpenStudioApplication: 1.4.0-rc2

### Context
There is a new dataset of ~900 future weather files that I would like to use to test out buildings in future time + RCP scenarios.

**Comment by jmarrec** [comment]
This has nothing to do with OpenStudioApplication, it's done in the OS SDK (which we depend on). So you should open an issue on [NREL/OpenStudio](https://github.com/NREL/OpenStudio/issues)

Also, just change your EPW header to have the extra S. The fact that E+ allows you to do it doesn't mean you should.
(E+ checks that the line starts with `HOLIDAYS/DAYLIGHT SAVING` (no S) but if you look at the error messages and the original EPW files they all have the extra S)
