### ISSUE TITLE
App crashes after viewing Results Summary tab

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#547]
Issue overview
--------------

After viewing the Results Summary tab, clicking on any other tab (eg. Run Simulation, Simulation Settings, etc.) will cause the app to crash.

## Current Behavior

It seems this tutorial for enabling the debug output messages needs to be updated.  The command 'set OPENSTUDIO_APPLICATION_LOGFILE_PATH=%USERPROFILE%\Desktop\osapp.log' did not work.  I had to direct it to another directory other than the user desktop.

Here is the debug output file:
[osapp.log](https://github.com/openstudiocoalition/OpenStudioApplication/files/8911989/osapp.log)

## Steps to Reproduce

1. Go to view the Results Summary tab
2. Click any other tab.
3.
4.

## Possible Solution

There may be a delay of the program loading the Results Summary tab and this is conflicting with the command to open another tab.  

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2022-06-14 (2)](https://user-images.githubusercontent.com/69771412/173896005-377e4276-b662-476b-92b7-b24f6c600088.png)

### Context

Occasionally, I am able successfully open another tab without the program crashing.  Otherwise, this is a major annoyance.  I have tried this on two different computers with different .osm files and it still crashes.

**Comment by macumber** [comment]
I just reproduced this too, this is a major pain.  I will look into it.

**Comment by jmarrec** [comment]
It does looks like a problem where we don't lock the tab while it loads indeed as Ski90Moo said... geez.

**Comment by macumber** [comment]
No fixes yet but it does seem that the crash occurs in `BrowserAccessibilityQt::~BrowserAccessibilityQt`.  I've noticed it doesn't seem to crash if you change tabs before the html fully loads.  That makes me think some accessibility thing is loaded/changed/etc at the very end of the page load and that is related to the crash.

**Comment by macumber** [comment]
I don't know why we are explicitly deleting the m_page and m_view [here ](https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/src/openstudio_lib/ResultsTabView.cpp#L142) since they are already parented by the view.  I commented those deletes out and still got the same crash.

**Comment by macumber** [comment]
@Ski90Moo could you try this test installer and see if the problem is fixed for you?

**Comment by Ski90Moo** [comment]
Yes, that seems to have fixed the problem. :)

**Comment by macumber** [comment]
Thanks for reporting and testing the fix!

**Comment by jmarrec** [comment]
> I don't know why we are explicitly deleting the m_page and m_view [here ](https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/src/openstudio_lib/ResultsTabView.cpp#L142) since they are already parented by the view. I commented those deletes out and still got the same crash.

That's a question for past you apparently :) https://github.com/NREL/OpenStudio/commit/33021d6e6251cead36b635406e00aabc97d940f9 .

Thanks for the fix @macumber and thanks for reporting and testing @Ski90Moo

**Comment by Ski90Moo** [comment]
Thanks for working on this guys! @macumber @jmarrec
