### ISSUE TITLE
Default Cooling Coil should be CounterFlow

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#581]
Issue overview
--------------

The default cooling coil OS:Coil:Cooling:Water from the HVAC library has ! Heat Exchanger Configuration as nil.  This is correct and should be translated to EnergyPlus as the default (CounterFlow for cooling coils).

However, when dropping the object into a loop using the OpenStudio App, the App appears to assign CrossFlow to the object (shown in the drop down menu).  Inspecting the osm file, it does not actually assign CrossFlow (it is still nil).  But, when the simulation is run, it gets translated to EnergyPlus as CrossFlow.

## Steps to Reproduce

1. Create air loop and drop in a chilled water coil.  App shows CrossFlow is selected:
![2022-12-12](https://user-images.githubusercontent.com/69771412/207015748-12de9346-2768-4ba7-b003-3ab6f057e743.png)

2. Inspecting the osm file, it shows nil:
![2022-12-12 (1)](https://user-images.githubusercontent.com/69771412/207015962-36a5c416-6c5b-4685-80e8-86798c710493.png)

3. Inspecting the idf input file, it shows CrossFlow:
![2022-12-12 (2)](https://user-images.githubusercontent.com/69771412/207016370-66924752-dba6-40e3-80d9-ebbca361661c.png)

4.
5.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2022-12-12 (4)](https://user-images.githubusercontent.com/69771412/207016685-23909d4b-31c6-4ea8-8170-e3b0eaed231c.png)

**Comment by macumber** [comment]
Thanks @Ski90Moo, this is an OS SDK issue so I posted this over at https://github.com/NREL/OpenStudio/issues/4772

As a work around in the meantime, you can select CrossFlow in the app and then select CounterFlow, this will hard assign the values in that field
