### ISSUE TITLE
Results do not show up 

### ISSUE THREAD

**Issue by muh182** [openstudiocoalition/OpenStudioApplication#592]
Issue overview
--------------
I've seen recently students receiving issue with the results as it does not show up properly. 

## Current Behavior
This page shows up:

<img width="1462" alt="Screenshot 2023-02-10 at 3 58 05 PM" src="https://user-images.githubusercontent.com/2249257/218206789-8e897157-0b16-4819-976b-d8cc4ed95b0e.png">

I did not get a chance to dive further to see the source but at least a few students are experiencing this issue this semester. 

It happens for both EnergyPlus and OpenStudio results. Removing the Results measure also does not fix it.

The workaround is to delete all the files in the folder except the floorplan file and re-run the model. After that the issue is gone. It might be because students move files around and some of the paths might get corrupted. 

## Expected Behavior
The results should show up with no issue.

### Environment
It happened on both Windows and Mac for Version 1.4.0 and 1.5.0

**Comment by jmarrec** [comment]
Can you zip and upload folder where this happens? Otherwise I'm not sure how we can reproduce this.
