### ISSUE TITLE
Report about "Update standards (add 90.1-2016 and 90.1-2019 library files) by @jmarrec in #587"

### ISSUE THREAD

**Issue by ZeroConsultingUser** [openstudiocoalition/OpenStudioApplication#593]
Report about "Update standards (add 90.1-2016 and 90.1-2019 library files) by @jmarrec in #587"

After updating the OS application 1.5.0 and OS 3.5.1 to use standards 90.1-2016 and 90.1-2019, these standards don´t appear to be introduced it to define space type or when you want to add loads or create baseline.

The libraries appear in the application... 
![image](https://user-images.githubusercontent.com/74355190/220677098-427415bb-5cb2-442a-9d08-7f8810002022.png)

...but not whe we try to use for a project.  

![image](https://user-images.githubusercontent.com/74355190/220677285-97f7cfaa-07a7-45cf-aa8a-351b98a917b4.png)

![image](https://user-images.githubusercontent.com/74355190/220677398-f694b563-f50c-4136-8807-588f62fb87f7.png)

Could it be possible that we have done something wrong? Or maybe the update should be reviewed. 

Thanks!

**Comment by jmarrec** [comment]
This is provided by the OS SDK, should be fixed by https://github.com/NREL/OpenStudio/pull/4850
