### ISSUE TITLE
Multiple 'un-magnifying glass' icons inside VRF system view

### ISSUE THREAD

**Issue by eringold** [openstudiocoalition/OpenStudioApplication#597]
Issue overview
--------------
![image](https://user-images.githubusercontent.com/10799524/230121330-91a5dd01-ad68-4260-8bc3-14bb3d7d669c.png)

## Current Behavior
Approximately 5.2 little un-magnifying glass icons appear.

## Expected Behavior
Just one little un-magnifying glass should appear.

## Steps to Reproduce

In HVAC tab, navigate to VRF view, add VRF system, click to enter into VRF system. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.5.0+2a9ad1764a

### Context
The whole thing is click-able, which honstly is kind of nice having a larger clickable area, but still it's weird.

**Comment by jmarrec** [comment]
I can make all buttons display 5 times everywhere if you want?

**Comment by jmarrec** [comment]
Fixed in https://github.com/openstudiocoalition/OpenStudioApplication/pull/598
