### ISSUE TITLE
Windows 10: Application fails on launch on new computer with "D:\OSN\src\utilities\blc\Local.cpp@74  Unable to update Local Database"

### ISSUE THREAD

**Issue by ARONDALTON** [openstudiocoalition/OpenStudioApplication#608]
Issue overview
--------------

The application fails on launch in on new computer with "D:\OSN\src\utilities\blc\Local.cpp@74  Unable to update Local Database"
Windows 10

I have tried many versions.  I thought maybe the data base was loaded in a previous version but not the updated one

## Current Behavior

On open the following screen is shown, followed by the next.

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/6592265/3bb55bbf-9309-44d3-a648-421241c23caf)
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/6592265/bd364347-eaee-4073-8637-ea4cfa3fa139)

### DEBUG log messages 
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/6592265/06aff509-f2e2-43cb-8a14-755780e11b70)
#### Gives:
openstudio.OSDocument] <-2> OSDocument::fixWeatherFileInTemp: 1
[openstudio.OSDocument] <-2> No weather file
[openstudio.LocalLibraryController] <-2> Creating LocalLibraryController with base app 00000099EC1FF590
[OSGridView] <-2> Creating cell wrapper row=0, col=0
[OSGridView] <-2> Creating cell wrapper row=0, col=1
[OSGridView] <-2> Creating cell wrapper row=0, col=2
[OSGridView] <-2> Creating cell wrapper row=0, col=3
[OSGridView] <-2> Creating cell wrapper row=0, col=4
[OSGridView] <-2> Creating cell wrapper row=0, col=5
[openstudio.bcl.LocalBCL] <1> Unable to prepare dbVersion 1.0/1.1 Statement
[openstudio.bcl.LocalBCL] <2> Unable to update Local Database
[OpenStudio] <2> An unhandled exception has occurred: D:\OSN\src\utilities\bcl\LocalBCL.cpp@74 : Unable to update Local Database
[removeDir] <-2> Removed 7 files

[osapp.log](https://github.com/openstudiocoalition/OpenStudioApplication/files/11503467/osapp.log)

## Expected Behavior

It should open the application!

## Steps to Reproduce

1. Turn Off the firewall and real-time scanning ( McAfee)
2. Download... https://github.com/openstudiocoalition/OpenStudioApplication/releases/download/v1.5.0/OpenStudioApplication-1.5.0+2a9ad1764a-Windows.exe  at
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/6592265/c51eb24e-10ef-413c-a4b2-b1fdea17b5bb)

3.  Try both the command line and icon to start the application
4.  Never gets past the second info box!

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):

Processor	Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz   3.40 GHz
Installed RAM	12.0 GB (11.9 GB usable)
Product ID	xxxxxxxxxxxxxxxxxxxxxxxx
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

### Context

I can not even start this application.  I do have an old Openstudio 2.9.1 running well

**Comment by macumber** [comment]
@ARONDALTON thanks for the report, that is not very good at all!  Can you run the following commands in a cmd window to list your username and home directory: `echo %username%` and `echo %userprofile%`.  Here is my output:

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/9c88ec60-0ebd-4ab0-8257-5b2016f78623)

The BCL library should be in that %userprofile% directory, do you have a folder named `BCL` in your home directory?

**Comment by ARONDALTON** [comment]
Thanks @macumber .

Yes. Is there an ini file that should point to this directory? 
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/6592265/40ab6aac-93c0-41a6-a578-c989775b665e)

**Comment by macumber** [comment]
What is the path of that directory?  I’m trying to see if you have non ascii characters in your username or if the directory is on a network drive or something like that

**Comment by macumber** [comment]
Also you seem to have downloaded new contents on 5/13, was that from this computer?  I also see old content from 2020, did you copy your bcl dir from your old computer to your new one?

**Comment by macumber** [comment]
My suggested solution would be to try removing the BCL library directory in your user directory.  You could just rename the directory to something else as a quick try
