### ISSUE TITLE
Crashes with assigning Summer/Winter Schedule

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#613]
Issue overview
--------------
Program crashes when creating a new summer/winter design day schedule for a fractional schedule type.

## Current Behavior
![OpenStudioApp_S08A5MKcnU](https://github.com/openstudiocoalition/OpenStudioApplication/assets/69771412/be690775-bb1e-4ea1-85f4-71c9fe2deaa7)

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution

I think there is a timing or pause error.  If I select the drop down and select a "new profile based on", and then click out, such as the schedule name, and then click the add button, it works.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2023-07-20 (1)](https://github.com/openstudiocoalition/OpenStudioApplication/assets/69771412/2caa41d6-6388-4a67-90fa-c9bb2e4b3bda)

**Comment by Ski90Moo** [comment]
Ok, most of the time it just crashes.  I'm not sure what the trick is to make it work.

**Comment by macumber** [comment]
Yeah, I can reproduce this.  I'll see if I can figure it out.

**Comment by macumber** [comment]
@Ski90Moo would you mind trying https://github.com/openstudiocoalition/OpenStudioApplication/suites/14505073196/artifacts/820150340 to verify that the issue is fixed?

**Comment by Ski90Moo** [comment]
Yes, this fixed it.

**Comment by jordibrunet** [comment]
Is there any way -or trick- to avoid this bug using OpenStudio Application 1.5 (without having to change app version)?

**Comment by jmarrec** [comment]
@jordibrunet yes, create the DD Summer and/or Winter schedule via the API. Example

```ruby
m = exampleModel  # here you would load your model instead
sch_ruleset = m.getScheduleRulesets.first
# setSummer/WinterDesignDaySchedule clones the ScheduleDay passed as argument
sch_ruleset.setSummerDesignDaySchedule(sch_ruleset.defaultDaySchedule)
sch_ruleset.setWinterDesignDaySchedule(sch_ruleset.defaultDaySchedule)
```

**Comment by jordibrunet** [comment]
Thanks, @jmarrec 

Is there any tutorial explaining how to access to OpenStudio API?

**Comment by jmarrec** [comment]
https://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/

See "Optional - Install Ruby" to setup an interactive prompt.

You can also write a script.rb file and launch the openstudio CLI on it directly if you don't want the hassle of setting up ruby.

example `script.rb`, place it next to your file, assuming it's called `model.osm`, and that the schedule you want to add winter/summer DD schedules if not already explicitly set is called `My Schedule`

```ruby
require 'openstudio'
include OpenStudio::Model

# Helper to load a model in one line
# It will raise if the path (or the model) isn't valid
#
# @param path [String] The path to the osm
# @return [OpenStudio::Model::Model] the resulting model.
def osload(path)
  translator = OpenStudio::OSVersion::VersionTranslator.new
  ospath = OpenStudio::Path.new(path)
  model = translator.loadModel(ospath)
  if model.empty?
      raise "Path '#{path}' is not a valid path to an OpenStudio Model"
  else
      model = model.get
  end
  return model
end

# Load
m = osload('model.osm')

# DO STUFF
sch_ruleset = m.getScheduleRulesetByName("My Schedule")
# setSummer/WinterDesignDaySchedule clones the ScheduleDay passed as argument
if sch_ruleset.isSummerDesignDayScheduleDefaulted
  sch_ruleset.setSummerDesignDaySchedule(sch_ruleset.defaultDaySchedule)
end
if sch_ruleset.isWinterDesignDayScheduleDefaulted
  sch_ruleset.setWinterDesignDaySchedule(sch_ruleset.defaultDaySchedule)
end

# Save
m.save('model.osm', true)
```

Usage: `openstudio script.rb`

Then reload your OSM in the OS App.

If you want to do it for **all** schedule rulesets, replace the "DO STUFF" section above with a for loop

m.getScheduleRulesets.each do |sch_ruleset|
  if sch_ruleset.isSummerDesignDayScheduleDefaulted
    sch_ruleset.setSummerDesignDaySchedule(sch_ruleset.defaultDaySchedule)
  end
  if sch_ruleset.isWinterDesignDayScheduleDefaulted
    sch_ruleset.setWinterDesignDaySchedule(sch_ruleset.defaultDaySchedule)
  end
end

**Comment by jordibrunet** [comment]
Thank you very much @jmarrec !

I had some problems with "isSummerDesignDayScheduleDefaulted", but modifing the code as above works! Maybe is something related to OS 1.5.0?

```ruby
# DO STUFF
sch_ruleset = model.getScheduleRulesetByName("My Schedule")
if sch_ruleset.is_initialized
  sch_ruleset = sch_ruleset.get
  default_day_schedule = sch_ruleset.defaultDaySchedule
  if sch_ruleset.isSummerDesignDayScheduleDefaulted
    sch_ruleset.setSummerDesignDaySchedule(default_day_schedule)
  end
  if sch_ruleset.isWinterDesignDayScheduleDefaulted
    sch_ruleset.setWinterDesignDaySchedule(default_day_schedule)
  end
else
  puts "Schedule 'My Schedule' not found in the model."
end
```
