### ISSUE TITLE
OSM geometry rendering doesn't reflect space origins (but IDF does)

### ISSUE THREAD

**Issue by shorowit** [openstudiocoalition/OpenStudioApplication#616]
Issue overview
--------------
I have a residential multifamily model where the three multifamily units are offset by 100 meters. This is accomplished by changing the spaces' y-axis origin value.

When I import the IDF, it correctly shows the units as offset. (_Ignore the fact that each unit is comprised of surfaces floating in space and don't look like an enclosed building model._)

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/5861765/33423a0c-35ab-4754-b8de-3d7e7a0e0c38)

But when I open the OSM from which the IDF was generated, the three units are right on top of each other.

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/5861765/336bc4ee-1295-466e-95c7-c83cb1ffd862)

I would expect to see the same rendering either way.

OSM: [in.osm.txt](https://github.com/openstudiocoalition/OpenStudioApplication/files/12155968/in.osm.txt)
IDF: [in.idf.txt](https://github.com/openstudiocoalition/OpenStudioApplication/files/12155969/in.idf.txt)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): v1.6.0

**Comment by macumber** [comment]
Hey @shorowit I'm not able to reproduce this.  When I open in.osm.txt I see three spaces, when I export to IDF and then re-import I see three spaces again.  When I import the in.idf.txt I see 9 spaces (units 0, 1, 2).  Are you sure in.osm.txt is the right input that generated in.idf.txt?  What process did you use to translate the in.osm.txt to in.idf.txt, did that process add the new spaces and translate their origins?

**Comment by shorowit** [comment]
Ugh, sorry @macumber, I think I must have used the wrong OSM. I tried again to reproduce the issue and now I get the correct behavior. I hope I didn't waste too much of your time! 😞

**Comment by macumber** [comment]
No worries, thanks Scott!
