### ISSUE TITLE
Can't find any file in the online BCL 

### ISSUE THREAD

**Issue by LucaMagoni** [openstudiocoalition/OpenStudioApplication#617]
Issue overview
--------------
Using ''find measures'' in the ''Components & Measures'' menu there are no file in the online BCL 

## Details
When starting the program there is a message that says ''Could not find or download Openstudio Results Measure''
### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

**Comment by macumber** [comment]
Thanks for the report @LucaMagoni, when this occurs do you have internet access?  Can you access the website https://bcl.nrel.gov/?  

If so, my suspicion is that your firewall or anti-virus programs may be blocking network traffic from OpenStudio.  Can you check that OpenStudio Application has access on private and public networks under the Windows firewall https://pureinfotech.com/allow-apps-firewall-windows-10/ ?



Also, which version of OpenStudio Application are you using?

**Comment by macumber** [comment]
Hmm, after clicking on browse in https://bcl.nrel.gov/browse it seems that the BCL may be down right now

**Comment by macumber** [comment]
I reported the BCL issue at https://github.com/BuildingComponentLibrary/bcl-manifest/issues/27

**Comment by ealexandraki** [comment]
Hello,
@macumber I have the same issue and it is causing my simulation to fail with exit code 1 because it cannot "find" the OS results measure. I created a separate issue for this but mentioning here since these issues seem connected. Thank you!

**Comment by macumber** [comment]
The BCL is back online so this instance should be resolved.  The change in #614 will allow using the offline results measure in case of a future BCL outage
