### ISSUE TITLE
Cannot find open studio results measure (msg when app launches & issue when running a simulation) 

### ISSUE THREAD

**Issue by ealexandraki** [openstudiocoalition/OpenStudioApplication#619]
Issue overview
--------------
When I open the OS application, I get a message that the open studio results measure cannot be found. When I try to run a simulation it fails with exit code 1, and the details show that the system cannot find the open studio results measure. I even tried pasting them locally into the "my measures" folder and that did not work either. This is strange because a few weeks ago I was able to run a simulation without such issues. Uninstalling and reinstalling the software makes no difference. Another note: when I try to find measures in the online BCL, no measures of any kind show up. My internet connection works and all permissions and firewalls seem to work fine as well, i.e. they are not blocking the app. Thanks for your help!

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

**Comment by macumber** [comment]
Thanks for the report @ealexandraki, I have a few more questions for you

- Was this a model that was previously working or is this a new model?
- Is the results measure in your simulation workflow on the scripts tab?
- Is the results measure listed in your library of measures on the scripts tab?
- Is the results measure in the measures folder of your OSM model's companion directory?
- Does the EnergyPlus simulation complete successfully (check the `run/eplusout.err` file in the companion directory)?

**Comment by macumber** [comment]
Is this the output you are seeing?

```
Processing Reporting Measures.
Applying OpenStudioResults
Result: Success
Initial Condition: Gathering data from EnergyPlus SQL file and OSM model. Will report in IP Units
Final Condition: Generated report with 22 sections to ./report.html.
Gathering Reports.
[07:50:25.405248 ERROR] Found error in state 'reporting_measures' with message ["920: NaN not allowed in JSON::/ruby/2.7.0/json/common.rb:286:in `generate'\n:/ruby/2.7.0/json/common.rb:286:in `pretty_generate'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/adapters/output/local.rb:111:in `block in communicate_measure_attributes'\neval:445:in `open'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/adapters/output/local.rb:110:in `communicate_measure_attributes'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_reporting_measures.rb:122:in `perform'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'\n:/openstudio_cli.rb:1187:in `execute'\n:/openstudio_cli.rb:817:in `execute'\n:/openstudio_cli.rb:1984:in `<main>'\neval:188:in `eval'\neval:188:in `require_embedded_absolute'\neval:173:in `block in require_embedded'\neval:167:in `each'\neval:167:in `require_embedded'\neval:126:in `require'\neval:3:in `<main>'"]}
Failed.
Simulation failed to run, with exit code 1
```

**Comment by lzwang26** [comment]
Hi,

I met the same issue on openstudioapplication-1.6.0. It firstly happened during the development and test of my own openstudio measure. And then never disappear. 

1. When I run the openstudio application, the first error message I see is shown below:
![Issue1](https://github.com/openstudiocoalition/OpenStudioApplication/assets/37538272/301db898-65c3-41a9-96b9-298167bbd168)
I cannot find and download any measure from the BCL.
2. After running the model, no matter succeed or fail, I see the following error message:
![Issue2](https://github.com/openstudiocoalition/OpenStudioApplication/assets/37538272/a46a8ca1-9156-4704-bab9-966657b777a5)
No files can be saved in the output folder.

I tried to uninstall and reinstall the openstudio applicaiton. But these issues still cannot be cancelled.

Hope these information help.

Thank you!

**Comment by lzwang26** [comment]
An additional information, I tried to install the older version openstudio application (1.5.0), the errors are still there.
Thank you!

**Comment by ealexandraki** [comment]
@macumber Thank you for the follow-up! Regarding your questions:

- Q1: This is a new model. I also tested a previous model (which had to get upgraded from a previous OS version) and I got the same error.
- Q2: I am not sure what the scripts tab is. Perhaps the replies bellow answer this. 
- Q3: I can select the measure from the Library, as shown in the screenshot below: 
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/64674062/5cd38131-97c1-4eba-8c31-f5efa8c436b4)
- Q4: If I click on the "my measures" (the blue icon that says "my") I do not see the open studio results measure. I tried pasting it in, and this does not work either, see screenshot of what I am referring to:
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/64674062/8456c10c-8337-484a-a897-08f6c2e26831)
- Q5: I do not get the Energy Plus error file. It seems to fail prior to that. I think at the "pre-process" step because I don't see a "in.idf" file either. This is what I see after clicking on "show simulation": 
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/64674062/bdfe82db-d817-4fcf-856f-265e2105c026)
- Q6: Here is a screenshot of the errors: 
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/64674062/d8be146f-9c19-4b24-9ea6-51cc8dfd3fdf)

Thank you for looking into this!

**Comment by ealexandraki** [comment]
@macumber UPDATE: I tried running a simulation again with 2 different files (now that the BCL is back online). Same errors and crashes appear.

Thank you for your help,
Eleni

**Comment by macumber** [comment]
@ealexandraki now that the BCL is back online, here is what I suggest you try:

1. Click on "My Measures" and delete the openstudio_results measure you pasted there
2. Restart OpenStudio
3. Click on "Find Measures on BCL" and download the OpenStudio Results measure (see image below)
4. Delete the current OpenStudio Results measure in your workflow (see second image below) and drag the OpenStudio Results measure with the BCL tag in to replace it (you might have to change tabs to refresh the measures after downloading)

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/75e72b5b-a015-48aa-a365-c1115677c10e)

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/5953b884-6ff6-42fc-b079-9f07c398c439)

Does that work?

**Comment by macumber** [comment]
@lzwang26 your problems seem different.  The BCL is back online which should resolve your first issue.  The second issue about failing to save the file is probably due to either 1) trying to save the file to a network location or 2) trying to save the file to a directory with non-English characters in the directory or filename. Can you try saving to a simple location like "C:\test\my.osm" to see if that resolves your issues?

**Comment by ealexandraki** [comment]
@macumber Thank you for your reply. I tried everything you mentioned, however I am not able to test it because every time I (1) try to save and (2) try to run the simulation I get the same note as @lzwang26 that I cannot save the file. This has been happening and sometimes I get the error and sometimes I do not (for the same files, in the same file location...). I will try again but this is also an issue that affects the workflow significantly.

Thank you,
Eleni

**Comment by macumber** [comment]
I am very sorry to hear about your problem.  I think this is due to corruption of the `workflow.osw` in your OSM model's companion directory, I was able to re-produce your error by referencing a bad measure in my `workflow.osw` file.  Can you copy your OSM and companion directory somewhere else, then in the new location open the `workflow.osw` file in a text editor. You can select all the content in the `steps` portion and delete it:

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/c9b0d666-17df-4c0c-a023-c08cf51b8185)

Afterwards your steps section should look like this:

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/7f048cd7-087b-49fe-b24b-4d9b791f42c7)

After that, you can open the new OSM and re-drag in measures as needed.  Does this help resolve the issue?

**Comment by ealexandraki** [comment]
@macumber I cannot locate the workflow.osw file. Could you please share my additional details in terms of where this file is stored? When I hit "run" no new files get created in the folder location of the .osm file. Also, I looked in the temp folder and could not find anything there either. The only workflow.osw file I have is the one for Open Studio for Revit 2024, which I believe is a completely separate thing... Thank you very much for the clarification!

**Comment by macumber** [comment]
If your OSM file is named "MyModel.osm", there should be a companion directory right next to it named "MyModel".  Inside that directory should be a file named "workflow.osw".

**Comment by ealexandraki** [comment]
@macumber oh right! I totally forgot about that folder, my bad. I tried the steps outlined and it worked for one file! The other one failed and produced the error file so I think I need to fix some things there. Overall, I think this resolved the issue! So, in general, should I keep checking the workflow.osw file so that it looks as shown in your last screenshot? Thank you.

**Comment by ealexandraki** [comment]
Adding to previous message: the cannot save error persists, and I have to try opening and running the file multiple times until one of these times (for whatever reason) works and the "failed to save" error does not pop up. That is, the simulation won't run when the error pops up.

**Comment by macumber** [comment]
You shouldn't ever have to modify the workflow.osw by hand.  The OpenStudio Application should keep that file up to date when you add, change, remove measures from your workflow. I suspect something went wrong when the BCL went offline and you tried changing the measure to your My Measures location.  

That would be super weird if the issue was intermittent on the same file.  Are you just opening the file and pressing the run simulation button?

**Comment by ealexandraki** [comment]
@macumber Yes, sometimes when I open the file (& re-set the weather file and ddy) and then press the run button, I get the error that the file cannot save. Because of this, the simulation won't run.  If I try this a bunch of times, then there's a chance one of the times it will not give the error and the simulation will start. This has happened randomly to two different files I have tested. I have also noticed that every time this happens, when I check the workflow.osw file there's some code within "steps", at which point I have been following your previous instructions and delete all the content ... would it be worth at this point to try re-installing the software one more time?

**Comment by lzwang26** [comment]
@ealexandraki You could try deleting the simulation generated folder before running the simulation. This folder should be generated under the same path and with the same name of the ".osm" file after each simulation. Sometimes when I modify the measure and test it multiple times, there will be different versions of the measure under the "measures" folder in this simulation generated folder. This may be the reason of the "file cannot save" error. I'm not pretty sure, but it works for me.

**Comment by ealexandraki** [comment]
@lzwang26 Thank you for the tip! Just tried it but it looks like I still get the same error unfortunately :/

**Comment by dmacusb2** [comment]
Reinstalling software won’t do anything here.  Note you have to close the OpenStudio Application before modifying any of the files or folders by hand.  Otherwise you run the risk that the app will just save the bad file content back over your changes.

**Comment by dmacusb2** [comment]
@lzwang26 which measure are you modifying?  Are you modifying the measure in the osm companion directory?  The expected workflow is to only modify measures in the My Measures directory then update them in your model by pressing the button that checks for updates

**Comment by ealexandraki** [comment]
@macumber Is there anything else I could try to resolve this? I have been editing the files with the app closed so I think this should not be an issue. Thank you!

**Comment by dmacusb2** [comment]
If you are able could you zip your osm file and companion dir and either upload to a post here or email to me at the email address in my profile?  I can take a look to see if I can reproduce any of your issues

**Comment by ealexandraki** [comment]
@macumber I cannot upload the particular file but have another one that I just checked has the same error. That is: I tried to run the simulation and I get the "cannot save" error. Uploading it here. Thank you!
[error-file-EleniAlexandraki.zip](https://github.com/openstudiocoalition/OpenStudioApplication/files/12353404/error-file-EleniAlexandraki.zip)

**Comment by macumber** [comment]
Somehow you have a corrupt OpenStudio Results measure.  The folder in the lower right shows the files in your measure at `EleniAlexandraki-ProblematicFile\measures\OpenStudioResults\resources`.  The folder on the lower right shows the files in the OpenStudio Results measure from https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/openstudio_results (attached here).

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/2bb95d4f-3b2f-4f5e-95cd-9f2d95747cf1)

My suggestion is to search your computer for instances of the bad OpenStudio Results measure and delete them.  You can also delete your local BCL database (should be located at `C:\Users\<username>\BCL` where <username> is your username).  After that you can re-download the OpenStudio Results measure using the OpenStudio Application and try again.

[openstudio_results.zip](https://github.com/openstudiocoalition/OpenStudioApplication/files/12354672/openstudio_results.zip)
