### ISSUE TITLE
2019 SketchUp Plugin for OSX

### ISSUE THREAD

**Issue by tijcolem** [openstudiocoalition/OpenStudioApplication#62]
Fix for Windows was: 
https://github.com/NREL/OpenStudioApplication/pull/50
https://github.com/NREL/openstudio-sketchup-plugin/pull/1

Need to move 2.x plugin logic to build model_editor for osx and test CI incremental installer.

**Comment by DavidGoldwasser** [comment]
This has been tested in the past, but I can leave open until I go through process with RC installers
