### ISSUE TITLE
Refactor HVACSystemsController to hide controls by default and enable them only when needed

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#625]
Enhancement Request
--------------

See @macumber 's comment here: https://github.com/openstudiocoalition/OpenStudioApplication/pull/622#discussion_r1306554723

## Detailed Description

Perhaps clearer and more maintanable to have the the controls hidden, then show + connect where appropriate.

**Comment by macumber** [comment]
This is a minor issue issue at best, I'd be ok to just close it
