### ISSUE TITLE
Window and door components are not placing on geometry in floorspace.js

### ISSUE THREAD

**Issue by YogeshGooljar** [openstudiocoalition/OpenStudioApplication#632]
Issue overview
--------------
Hi, I am new to OpenStudio. I am currently learning how to use the Openstudio application (I have downloaded version 1.60 for Windows). I have created a simple geometry on floorspace.js. I have been able to add doors and windows on Story 1 but as soon as I try to add a window or door component on any other Story, it does not work. It seems that I can only add windows and doors on the ground floor (Story 1). I have tried to merge my model with current OSM and try again...but same issue. For windows, I can find a work-around by adding a higher sill height but cannot use the same trick to doors. The window or door icon does not show at all for me to place it on the geometry on any other story than story 1. Please help!

## Current Behavior
I cannot place any new window or door component on the geometry apart from Story 1. 
-->

## Expected Behavior
I should be able to create a new window or door and place it on Story 2 and above, when I am on the corresponding layout. 

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.6.0+53c249a897

### Context
I cannot use the OpenStudio application without being able to use the floorspaceJS geometry builder. 
![Screenshot 2023-09-13 100534](https://github.com/openstudiocoalition/OpenStudioApplication/assets/144891831/81401fdb-22d5-4b48-b48f-3b41aa273bde)

**Comment by macumber** [comment]
This seems to be a result of https://github.com/NREL/floorspace.js/issues/416

**Comment by macumber** [comment]
Does this occur only when you duplicate story 1 to story 2?  What happens if you add a blank story 2 and trace over story 1?

**Comment by macumber** [comment]
@YogeshGooljar note that making the sill height very high will position windows correctly in space but it won't associate them with the correct spaces/thermal zones on the second story.  The loads from those windows with high sill heights will all go into the first story spaces and thermal zones.

**Comment by YogeshGooljar** [comment]
> Does this occur only when you duplicate story 1 to story 2? What happens if you add a blank story 2 and trace over story 1?

@macumber It doens't work either way, i,e whether I duplicate the story or insert a new blank story.

**Comment by YogeshGooljar** [comment]
> @YogeshGooljar note that making the sill height very high will position windows correctly in space but it won't associate them with the correct spaces/thermal zones on the second story. The loads from those windows with high sill heights will all go into the first story spaces and thermal zones.

@macumber Thank you for highlighting this. Then I am back to square 1.

**Comment by YogeshGooljar** [comment]
Stories have to be created from new and windows added per story. 
Windows cannot be added if story has been duplicated.
