### ISSUE TITLE
Viewing HVAC Systems Control view resets Controller:MechanicalVentilation System Outdoor Air Method

### ISSUE THREAD

**Issue by eringold** [openstudiocoalition/OpenStudioApplication#634]
Issue overview
--------------
Loading a model with a Controller:MechanicalVentilation with 'System Outdoor Air Method' set to 'Standard62.1VentilationRateProcedureWithLimit' and navigating to the HVAC Systems Control tab will cause that input to be reset.

## Expected Behavior
Input should be retained.

## Steps to Reproduce

1. Create and save a model with an AirLoopHVAC with OA System and Controller:MechanicalVentilation with System Outdoor Air Method set to 'Standard62.1VentilationRateProcedureWithLimit'.
2. Open model in OSApp, navigate to HVAC Systems tab, Control view. Model change indicator (asterisk by filename) will appear.
3. Save as, do file compare with original.

## Possible Solution
Issue very similar to https://github.com/openstudiocoalition/OpenStudioApplication/issues/379, therefore I suspect the fix will involve updating the `addItem` calls to `ventilationCalcMethodComboBox`: https://github.com/openstudiocoalition/OpenStudioApplication/blob/ecfb73422b50f386f2f5223ed9a377a28cc2baad/src/openstudio_lib/HVACSystemsView.cpp#L555-L560

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Window 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.6.0

**Comment by jmarrec** [comment]
@eringold Are you still planning on providing a fix for this?
