### ISSUE TITLE
Unable to find openstudio measures.

### ISSUE THREAD

**Issue by jliu268** [openstudiocoalition/OpenStudioApplication#640]
Issue overview
--------------

After downloading the openstudio application, I opened the application in order to use it. 
I did this by clicking on the application, and it opened up as intended. However after opening it displayed this message

## Current Behavior

![Screenshot 2023-11-13 193251](https://github.com/openstudiocoalition/OpenStudioApplication/assets/123121041/f9551e88-f651-4c08-9088-2de41ade0bee)

## Expected Behavior

I do not actually know what should happen as I am unable to go further in the program.

## Steps to Reproduce

1. Download the openstudio 1.6 version
2.Open the application. 
3.Error shows up.
4.

## Possible Solution

I 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

**Comment by macumber** [comment]
That error means that the OpenStudio Application wasn't able to download the OpenStudio Results measure which is a common measure for viewing simulation results.  The application is still usable without the OpenStudio Results measure, you just won't see the html pages generated by the OpenStudio Results measure.  

To get the OpenStudio Results measure from the BCL you will need access to the internet.  You will want to make sure your OS or anti-virus isn't blocking network access for the OpenStudio Application.  You could try opening the Components and Measures menu to search for and download the OpenStudio Results measure manually:

https://openstudiocoalition.org/reference/openstudio_application_interface/#components-measures-menu

**Comment by macumber** [comment]
Will be closed with https://github.com/openstudiocoalition/OpenStudioApplication/issues/641
