### ISSUE TITLE
Unknown CMake command "conan_check" ?

### ISSUE THREAD

**Issue by csyw** [openstudiocoalition/OpenStudioApplication#655]
CONAN_PRINT_RUN_COMMANDS: 
CMake Error at ConanInstall.cmake:35 (conan_check):
  Unknown CMake command "conan_check".
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

**Comment by macumber** [comment]
Which platform are you trying to build OpenStudio Application on?  Are you starting with a past build directory or from scratch?  

My first suggestion is to go through the instructions to configure the build environment at https://github.com/openstudiocoalition/OpenStudioApplication/wiki/Configuring-OpenStudio-Application-Build-Environments.  

When you configure, CMake should be downloading the file from
https://raw.githubusercontent.com/conan-io/cmake-conan/0.18.1/conan.cmake to your build directory, does that file exist for you?

**Comment by jmarrec** [comment]
Closing. If you need additional help after following the instructions, feel free to write here though!

**Comment by csyw** [comment]
thanks. My environment is VS2022, cmake 3.28 and conan 1.62.0，I built the project from scratch. According to the guidelines you provided, the following errors are currently occurring。

boost/1.79.0: Already installed!

boost/1.79.0: Disabled magic autolinking (smart and magic decisions)

libiconv/1.16: Applying build-requirement: msys2/cci.latest

libiconv/1.16: WARN: Build folder is dirty, removing it: C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

libiconv/1.16: Copying sources to build folder

libiconv/1.16: Building your package in C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

libiconv/1.16: Generator txt created conanbuildinfo.txt

libiconv/1.16: Aggregating env generators

libiconv/1.16: Calling build()

libiconv/1.16: 

libiconv/1.16: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
libiconv/1.16: WARN: Build folder C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

ERROR: libiconv/1.16: Error in build() method, line 145
	with self._build_context():

CMake Error at build/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  ConanInstall.cmake:186 (conan_cmake_install)
  CMakeLists.txt:81 (include)

At first, I thought it was an issue with the CMake or Conan versions. Then I tried to make changes to several versions (1.4X, 1.5X, 1.62, 2.0...), but none of them solved the problem. In addition, I am unable to compile libconv1.60 using Connan alone and have received the error message above. I‘m not sure where the problem lies, so how can i solve it ?

**Comment by csyw** [comment]
thanks. My environment is VS2022, cmake 3.28 and conan 1.62.0，I built the project from scratch. According to the guidelines you provided, the following errors are currently occurring。

boost/1.79.0: Already installed!

boost/1.79.0: Disabled magic autolinking (smart and magic decisions)

libiconv/1.16: Applying build-requirement: msys2/cci.latest

libiconv/1.16: WARN: Build folder is dirty, removing it: C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

libiconv/1.16: Copying sources to build folder

libiconv/1.16: Building your package in C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

libiconv/1.16: Generator txt created conanbuildinfo.txt

libiconv/1.16: Aggregating env generators

libiconv/1.16: Calling build()

libiconv/1.16: 

libiconv/1.16: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
libiconv/1.16: WARN: Build folder C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

ERROR: libiconv/1.16: Error in build() method, line 145
	with self._build_context():

CMake Error at build/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  ConanInstall.cmake:186 (conan_cmake_install)
  CMakeLists.txt:81 (include)

At first, I thought it was an issue with the CMake or Conan versions. Then I tried to make changes to several versions (1.4X, 1.5X, 1.62, 2.0...), but none of them solved the problem. In addition, I am unable to compile libconv1.60 using Connan alone and have received the error message above. I‘m not sure where the problem lies, so how can i solve it ?

**Comment by csyw** [comment]
thanks. My environment is VS2022, cmake 3.28 and conan 1.62.0，I built the project from scratch. According to the guidelines you provided, the following errors are currently occurring。

boost/1.79.0: Already installed!

boost/1.79.0: Disabled magic autolinking (smart and magic decisions)

libiconv/1.16: Applying build-requirement: msys2/cci.latest

libiconv/1.16: WARN: Build folder is dirty, removing it: C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

libiconv/1.16: Copying sources to build folder

libiconv/1.16: Building your package in C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

libiconv/1.16: Generator txt created conanbuildinfo.txt

libiconv/1.16: Aggregating env generators

libiconv/1.16: Calling build()

libiconv/1.16: 

libiconv/1.16: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
libiconv/1.16: WARN: Build folder C:\Users\.conan\data\libiconv\1.16\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

ERROR: libiconv/1.16: Error in build() method, line 145
	with self._build_context():

CMake Error at build/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  ConanInstall.cmake:186 (conan_cmake_install)
  CMakeLists.txt:81 (include)

At first, I thought it was an issue with the CMake or Conan versions. Then I tried to make changes to several versions (1.4X, 1.5X, 1.62, 2.0...), but none of them solved the problem. In addition, I am unable to compile libconv1.60 using Connan alone and have received the error message above. I‘m not sure where the problem lies, so how can i solve it ?

**Comment by jmarrec** [comment]
Can you give a full log?

You must use conan <2 (1.62.0 is fine).

Also, what do you get when you type `conan profile show default` .


When you try this, are you in a VS developer prompt (or did you call vcvarsall.bat or similar to load it?)?
