### ISSUE TITLE
Application crash when using Python measures without Python Bindings component installed

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#656]
Issue overview
--------------
Attempting to drag a Python measure into a workflow will throw an exception if the Python bindings are not installed.

## Current Behavior
Instead of showing an error, the uncaught exception will prompt the user to restart the application or close it, appearing like a crash.

## Expected Behavior
Measure should be seen with an arguments can't be computed error or something similar instead of an app crash.

## Steps to Reproduce
1. Install OpenStudio Application without Python bindings
2. Create a Python measure
3. Drag Python measure into workflow

## Possible Solution
Catch the error and display error instead of throwing exception.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.7.0-rc1

**Comment by jmarrec** [comment]
See also Reported by @brgix here https://github.com/openstudiocoalition/OpenStudioApplication/issues/653#issuecomment-1872964638

**Comment by jmarrec** [comment]
FWIW, the same thing happens in the OS SDK CLI.

**Comment by macumber** [comment]
Partially addressed this by changing the default to install Python bindings in https://github.com/openstudiocoalition/OpenStudioApplication/pull/662/files

**Comment by macumber** [comment]
Related to https://github.com/openstudiocoalition/OpenStudioApplication/issues/671
