### ISSUE TITLE
Better feedback from measures using new CLI

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#660]
Enhancement Request
--------------
Reported by @brgix here https://github.com/openstudiocoalition/OpenStudioApplication/issues/653#issuecomment-1872964638

**Comment by macumber** [comment]
I think you only see the info and debug statements from the measure if the verbose box is checked.  I think info statements should be seen in non-verbose mode from the CLI.  The formatting is bad and doesn't really help understand what is going on.  Also the progress bar isn't working, I think we need use the socket and update the progress bar on the new steps.

**Comment by macumber** [comment]
I'm not really sure if the socket option is supported by the new CLI.  The option is present in the CLI help but doesn't seem to work, I don't see where it is used in the source either.  @jmarrec do you know if the socket option is supposed to work for the new CLI?

**Comment by macumber** [comment]
Related to https://github.com/NREL/OpenStudio/issues/5069

**Comment by jmarrec** [comment]
@macumber I filed:

* https://github.com/NREL/OpenStudio/issues/5073
