### ISSUE TITLE
Crash when using OS:GroundHeatExchanger:HorizontalTrench

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#661]
Issue overview
--------------
Reported by @brgix here https://github.com/openstudiocoalition/OpenStudioApplication/issues/653#issuecomment-1872964638

**Comment by brgix** [comment]
My bad - issue already opened [here](https://github.com/openstudiocoalition/OpenStudioApplication/issues/649).

**Comment by jmarrec** [comment]
Closed in favor of #649
