### ISSUE TITLE
Mark Python measures as in error if using classic CLI

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#671]
Enhancement Request
--------------
Classic CLI cannot run Python measures.  If Python measures are in the workflow, add error badge if using the Classic CLI along with a message saying "Cannot use Python measures with the Classic CLI".

Should also hide Python measures in library if the Measure Manager is launched with the Classic CLI.

**Comment by jmarrec** [comment]
Did #720 address this as well or not?

**Comment by macumber** [comment]
The classic CLI is no longer used for MeasureManager so "Should also hide Python measures in library if the Measure Manager is launched with the Classic CLI." is fixed

But the "If Python measures are in the workflow, add error badge if using the Classic CLI" is not fixed
