### ISSUE TITLE
BCL Viewer Human Readable Descriptions

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#672]
Enhancement Request
--------------

It would be really helpful if the Readme files or human readable description and/or human readable description of modeling approach could be displayed when searching the BCL.  As it is, the data displayed is not very descriptive or helpful.  

This is also a problem with the BCL browser online.  Many of the descriptions are cut off; you must download the measure to actually figure out what it is.

## Detailed Description

![Screenshot 2024-01-22 091829](https://github.com/openstudiocoalition/OpenStudioApplication/assets/69771412/e501426b-5a07-4537-ad06-f92ffa7f0d44)

**Comment by jmarrec** [comment]
Definitely doable, and definitely a good idea. Thanks for the report.

**Comment by macumber** [comment]
Thanks, I agree.  I'd also like the UUID, VersionUID, and date changed listed

**Comment by jmarrec** [comment]
Related: https://github.com/NREL/OpenStudio/issues/5125
