### ISSUE TITLE
OpenStudio Application unusable on MacOS14 with M2

### ISSUE THREAD

**Issue by bwinsatt** [openstudiocoalition/OpenStudioApplication#688]
Issue overview
--------------
Opening an existing model will cause the application to crash. Navigating the application will also cause it to crash.

## Current Behavior
When the application is first opened, and I navigate to file>open and select an existing model, the application will ask if I want to save the existing model. I select "Don't Save" (because this is a blank model after just opening the app) and the Application crashes. This happens with any model, even the built in example model from File>Examples>Example Model.

I tried to see if I could create a model and save, and after creating a floorspace, I navigated to the first screen (Site) and the application crashed.

I attempted to enable DEBUG log and followed the instructions provided, but am not very familiar with command line interface and received an error that the directory could not be found. This is after opening the Terminal within the OpenStudioApp folder in Finder.

## Expected Behavior
The Application should open a model file.

## Steps to Reproduce

Example model: https://github.com/NREL/OpenStudio/blob/develop/resources/Examples/compact_osw/files/seb.osm

1. Open OpenStudio Application
2. File>Open>"Any OpenStudio model" OR File>Examples>Example Model

## Possible Solution
OpenStudio Application 1.6. worked fine without any crashes.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): MacOS14 on an M2 Macbook
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.7.0

**Comment by macumber** [comment]
On Mac the commands would be:

```
mac@~$ cd /Applications/OpenStudioApplication-1.7.0/
mac@OpenStudioApplication-1.7.0$ export OPENSTUDIO_APPLICATION_DEBUG=1
mac@OpenStudioApplication-1.7.0$ ./OpenStudioApp.app/Contents/MacOS/OpenStudioApp 
```

If you can send the output of that including the crash it will really help to diagnose the issue.

**Comment by bwinsatt** [comment]
Thanks for the instructions. See the attached debug report.
[OpenStudioApp_Debug.txt](https://github.com/openstudiocoalition/OpenStudioApplication/files/14547473/OpenStudioApp_Debug.txt)

**Comment by bwinsatt** [comment]
Correct, I installed the arm64 version.

**Comment by mioruggieroguida** [comment]
@jmarrec Having the same issues with M1 and version 1.7. Previous versions work fine.

**Comment by macumber** [comment]
@bwinsatt or @mioruggieroguida do either of you happen to have the OpenStudio Application set to use a language other than English?  Is your Mac using a language other than English?

**Comment by macumber** [comment]
Just to be sure we are all using the same version, can you take a screenshot of your Help->About dialog?  We did re-release 1.7.0 and I want to make sure you and I have the same version.

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/a97824e4-ee55-404c-88a7-cf39b86cac8d)

I do only have an M1 Mac Mini, I don't have access to an M2 yet.

**Comment by macumber** [comment]
It looks like this might be related to this Qt bug https://bugreports.qt.io/browse/QTBUG-120469

I can try updating to 6.6.2 and see if that fixes the issue for you

**Comment by macumber** [comment]
@bwinsatt @mioruggieroguida if you are able to download and install https://github.com/openstudiocoalition/OpenStudioApplication/actions/runs/8316866444/artifacts/1333384380 to see if that fixes your issues that would be really helpful to me since I can't reproduce the crash locally

**Comment by mioruggieroguida** [comment]
> @bwinsatt or @mioruggieroguida do either of you happen to have the OpenStudio Application set to use a language other than English? Is your Mac using a language other than English?
> 
> I can see `m_currLang=[en]` in @bwinsatt output so the language is not likely the issue, sorry for bugging you about it

@macumber My mac is set to English only.

**Comment by mioruggieroguida** [comment]
> Just to be sure we are all using the same version, can you take a screenshot of your Help->About dialog? We did re-release 1.7.0 and I want to make sure you and I have the same version.
> 
> ![image](https://private-user-images.githubusercontent.com/1327850/313488505-a97824e4-ee55-404c-88a7-cf39b86cac8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDM1ODgsIm5iZiI6MTcxMDc0MzI4OCwicGF0aCI6Ii8xMzI3ODUwLzMxMzQ4ODUwNS1hOTc4MjRlNC1lZTU1LTQwNGMtODhhNy1jZjM5Yjg2Y2FjOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDYyODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU4OWU3ZjU1YzA0ZTQzMDE3OTMzNjg4ODYyMTY0Mzc2Mzg0MzQzZjM1OGQ4ODhkZjMwYjlmZTdiOTIxM2VjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7GhiWuiGz9sFX5MhvvJu1AwZaR1NObgRBj0MCk-tBMY)
> 
> I do only have an M1 Mac Mini, I don't have access to an M2 yet.

<img width="407" alt="image" src="https://github.com/openstudiocoalition/OpenStudioApplication/assets/110836551/9ef6fafd-2ed6-40e2-8dc1-de39eb20f80b">

**Comment by mioruggieroguida** [comment]
> @bwinsatt @mioruggieroguida if you are able to download and install https://github.com/openstudiocoalition/OpenStudioApplication/actions/runs/8316866444/artifacts/1333384380 to see if that fixes your issues that would be really helpful to me since I can't reproduce the crash locally

@macumber I have downloaded and done some basic testing. All seems to work as expected. The new `search` feature is great BTW!

Not sure if this is related to the new version or simply there is more debug shown during the simulation, but I have noticed these errors when running the simulation on the same model 

```
Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff 1 from field 1, but that object cannot be located.
Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional 1 from field 1, but that object cannot be located.
```

**Comment by jmarrec** [comment]
@mioruggieroguida that's not an OSApp message, it's issued by the ForwardTranslator of the OpenStudio SDK. Feels free to open an issue on https://github.com/NREL/OpenStudio including this snippet of code if that bothers you

```
$ openstudio -e "m = OpenStudio::Model::Model.new; ft = OpenStudio::EnergyPlus::ForwardTranslator.new(); ft.translateModel(m)"

[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.
[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Discrete', points to an object named OnOff from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff 1 from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional from field 1, but that object cannot be located
```

**Comment by jmarrec** [comment]
Should be fixed via https://github.com/NREL/OpenStudio/pull/5117
