### ISSUE TITLE
Default is missing ZoneAirDistribution object

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#694]
Issue overview
--------------

I think it may be applicable to the SDK to EnergyPlus translator....

When adding HVAC systems to the model, the model does not automatically detect and create a DesignSpecification:ZoneAirDistribution object.  The causes the following error:

** Warning ** GetOAControllerInputs: Controller:MechanicalVentilation="CONTROLLER MECHANICAL VENTILATION 1"
   **   ~~~   ** Cannot locate a matching DesignSpecification:ZoneAirDistribution object for Zone="TZ:01-FCU-31-BAKERY-DINING".
   **   ~~~   ** Using default zone air distribution effectiveness of 1.0 for heating and cooling.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution

To solve this problem, I have always gone to the Thermal Zones tab, Heating Sizing Parameters, and adjusted the Design Zone Air Distribution Effectiveness in Heating Mode to 0.8.  For some reason, this triggers the program to inject a DesignSpecification:ZoneAirDistribution obejct into the final idf file.  It modifies the .osm file to include:

  ,                                       !- Zone Humidistat Dehumidification Set Point Schedule Name
  ,                                       !- Zone Humidistat Humidification Set Point Schedule Name
  ,                                       !- Design Zone Air Distribution Effectiveness in Cooling Mode
  0.8;                                    !- Design Zone Air Distribution Effectiveness in Heating Mode

This has been fine for me, because it always reminds me to adjust the air distribution effectiveness because my designs normally have overhead air distribution.  However, for new users, this will be a source of confusion and frustration.  At the very least, I think if a thermal zone is created, it should include these fields with null values.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/69771412/69458dfb-2c03-4806-9f13-9b43c71eb34c)

**Comment by jmarrec** [comment]
@Ski90Moo definitely not an OS App "issue", but a SDK one. The DSZAD is added to the IDF only if any of the fields on the Sizing:Zone object are non-defaulted: https://github.com/NREL/OpenStudio/blob/9165cdc1f5e42d8ea33c2fe3a428a7b48025d76b/src/energyplus/ForwardTranslator/ForwardTranslateSizingZone.cpp#L195-L208

**Comment by jmarrec** [comment]
Lol, I was going to create a ticket on NREL/OpenStudio, and look what I found @Ski90Moo :) Looks like we've had the same conversation you and I a year ago!

https://github.com/NREL/OpenStudio/issues/4876
