### ISSUE TITLE
Local copy of BCL folder gets wiped/overwritten

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#696]
Issue overview
--------------

Often, when I am adding a measure from the BCL online, it asks me to update my local files with the latest.  When I click ok, it completely wipes all of my local BCL files from the BCL folder and I am left with just the one or two that I just downloaded.  I then have to search for and redownload all of the measures that I previously had.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/69771412/6775d276-2c3b-4083-8f2e-0f696180d4a9)

### Context

This is a major hassle.

**Comment by macumber** [comment]
I'll take a look at this one

**Comment by Ski90Moo** [comment]
It is strange.  Sometimes it happens, sometimes not.  I have noticed that it seems to coincide with times that I upgrade to a newer version of OpenStudio.

**Comment by Ski90Moo** [comment]
I just thought of something...when I download the latest version of the App, I normally rename the "OpenStudioApp.exe" file in the bin folder to something like "OpenStudio_v3.7.0.exe".  This is so I can select the version I want from the windows start menu (it is confusing if all the versions are labeled "OpenStudioApp.exe").  Maybe this is causing problems?
