### ISSUE TITLE
Update to Qt 6.6.3

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#701]
Enhancement Request
--------------

Qt 6.6.3 was released 4 days ago, and will be the latest in the Qt 6.6 series.

it's a bug fix release, so should be a seemless update

https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.6.3/release-note.md

**Comment by macumber** [comment]
Good by me, I can work on it unless you are @jmarrec, I assume you'd want this for the 1.7.1 patch?
