### ISSUE TITLE
No response after online bcl selects categories

### ISSUE THREAD

**Issue by dandeline** [openstudiocoalition/OpenStudioApplication#707]
Issue overview
--------------

After opening the online BCL and choosing one of the categories, the software will remain unresponsive.

## Steps to Reproduce

1. open the Openstudio Application
2. choose Measures
3. choose "find measures on bcl"
4. choose envelope (then crashed)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): win11 23H2
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): openstudio 1.7.0 and 1.7.1

**Comment by bwinsatt** [comment]
I am also seeing this error, though my app is not crashing. Find measures on BCL never loads any measures, however, when I close BCL, my existing measures still update. Issue seen on OSApp 1.7.1, 1.7.0 and 1.6.0

**Comment by macumber** [comment]
Thanks for the report, my first guess would be something like your OS or anti-virus are blocking the web connections used to check for measures on the BCL.  Could one of you try running with the following commands to get debug output?

https://github.com/openstudiocoalition/OpenStudioApplication/wiki/Enable-debug-output-messages-for-the-OpenStudioApplication#windows

**Comment by macumber** [comment]
Hmm, I am able to reproduce this myself now, that makes me wonder if the BCL has gone down or changed somehow.  I will look into it

**Comment by macumber** [comment]
It looks like there is something wrong with the certificate for https://bcl.nrel.gov/, that is likely the root cause of this issue.  I filed this issue, https://github.com/NREL/bcl-gem/issues/28, the maintainers of bcl.nrel.gov will likely have to renew the certificates for the website.

**Comment by macumber** [comment]
The BCL was down 4/6-4/7 due to power outage at NREL (high winds forced the utility to de-energize power lines to avoid wildfires, yikes!).  However, after that the BCL query we have been using has stopped working.  I asked NREL to look into it, depending on their response we may have to update our BCL queries.  I think we should hold off on the 1.7.1 patch until this is resolved.

**Comment by macumber** [comment]
The BCL has been fixed and this should now be working agin

**Comment by macumber** [comment]
@dandeline if you are still having the issue with the app crashing we can re-open that and make this issue just about the app crash

**Comment by dandeline** [comment]
> @dandeline if you are still having the issue with the app crashing we can re-open that and make this issue just about the app crash

sorry for the late response, I just tried it and it works. Thanks a lot
