### ISSUE TITLE
Disable classic CLI option if not working

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#716]
Issue overview
--------------
Measure manager is not working in the classic CLI in 3.8.0, https://github.com/NREL/OpenStudio/issues/5212

Need to either disable the option to use classic CLI or update to version of CLI where it is working

## Current Behavior
Measure Manager crashes on launch and the app is not usable

**Comment by macumber** [comment]
@jmarrec I think even the non-classic measure manager is not working correctly.  I get this every time I open the app:

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/9d8cc0cf-6698-4584-9d44-0f553600ffeb)

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/0ceb8a6f-4819-4223-b975-c8fcc97d525b)

**Comment by jmarrec** [comment]
Yeah I explained why in https://github.com/NREL/OpenStudio/issues/5212#issuecomment-2133964548

We'll get that sorted soon

**Comment by macumber** [comment]
Going to remove option to use classic mode for measure manager
