### ISSUE TITLE
Add space infiltration design flow rate schedule selection at space level

### ISSUE THREAD

**Issue by jzsustain** [openstudiocoalition/OpenStudioApplication#721]
Enhancement Request
--------------
Add a dropdown to assign a schedule to the SpaceInfiltration:DesignFlowRate object at the space level. 

## Detailed Description
Schedules can be assigned by space type but not at the individual space in the interface.

Currently the only way to assign a schedule to the SpaceInfiltration:DesignFlowRate object at the space level is by opening the OSM file in a text editor or assigning it using a measure. 

## Possible Implementation
A dropdown to select a schedule should be a simple, straightforward solution for this.

**Comment by jmarrec** [comment]
I don't think that's the issue really.

I can assign a schedule in the drop zone for a space level infiltration: 

![image](https://github.com/user-attachments/assets/d6ee3488-901c-4601-84bd-977a539f84b3)

**Comment by jmarrec** [comment]
The schedule must have the right ScheduleTypeLimits though.

And one actual issue is that it's currently impossible to drag a new infiltration object from the library into the "Definition" dropzone.

**Comment by jmarrec** [comment]
![setting_space_infiltration_schedule](https://github.com/user-attachments/assets/1b1419a1-a05a-41d5-b19f-aca5533a38b0)

**Comment by jzsustain** [comment]
Thanks for the response. Forgot the schedules were set in the loads tab. Was looking in the airflow tab.
