### ISSUE TITLE
[v1.8.0-rc2] Bundled openstudio_results measure is at wrong location

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#736]
Issue overview
--------------

On first launch,  Getting "Could not find or download OpenStudio Results Measures"

![image](https://github.com/user-attachments/assets/5a676bd2-83ac-4757-9aad-6237f1318aa6)

Diagnostics:

* I redid the clean install on the clean VM. I can see after install that it has installed the openstuido_results measure, but probably with a duplicated folder/level, at 

```
$ ls /usr/local/openstudioapplication-1.8.0-rc2/Resources/openstudio_results/openstudio_results/
LICENSE.md  measure.rb  measure.xml  README.md  README.md.erb  resources  tests
```

Indeed, launching with `OPENSTUDIO_APPLICATION_DEBUG=1 /usr/local/openstudioapplication-1.8.0-rc2/bin/OpenStudioApp` I get this printed:

```
[utilities.bcl.BCLXML] <2> '/usr/local/openstudioapplication-1.8.0-rc2/Resources/openstudio_results/measure.xml' does not exist
[utilities.bcl.BCLMeasure] <2> '/usr/local/openstudioapplication-1.8.0-rc2/Resources/openstudio_results' is not a measure
```

## Possible Solution

Fixup the cmake

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 22.04, .deb installer, clean VM
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): v1.8.0-rc2

### Context

* #735

**Comment by macumber** [comment]
I did test this, the test install on my computer has `C:\openstudioapplication-1.8.0\Resources\openstudio_results\measure.xml`.  I probably broke it in https://github.com/openstudiocoalition/OpenStudioApplication/pull/720/commits/06a3a6bd02f1d9b3e5ef3d315a0bd0cae686c7fc#diff-3e0e7d9040c69c7312cc9765c646281ec373ef0b11a098c8863e33216d629e3f or https://github.com/openstudiocoalition/OpenStudioApplication/pull/720/commits/49e8cc2adca36ce51d246f900dce3a561f90f18d

I'll try fixing it
