### ISSUE TITLE
v1.8.0 does not appear to be compatible with BCL measure

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#750]
Issue overview
--------------

apply now BCL measure "ZEDG VRF with DOAS" https://bcl.nrel.gov/content/633b8efc-7bcb-4aa0-8821-d0ee08f960db 
works for version 1..7.1
**does not** work for version 1.8.0rc3

see also: https://github.com/NREL/openstudio-aedg-gem/issues/44#issuecomment-2334276342
## Current Behavior

![image](https://github.com/user-attachments/assets/6469b4ec-eb2a-40c6-a3b0-48253bfa9a1e)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![image](https://github.com/user-attachments/assets/edca202c-5970-4113-b367-da43dac761a7)

**Comment by macumber** [comment]
I think this is an issue with the AEDG measures, so would be best covered by your issue at https://github.com/NREL/openstudio-aedg-gem/issues/44.  I think this will be fixed in https://github.com/NREL/openstudio-aedg-gem/pull/43
