### ISSUE TITLE
Support Debian

### ISSUE THREAD

**Issue by fluxion-t** [openstudiocoalition/OpenStudioApplication#763]
Enhancement Request
--------------
Ubuntu is a derivative of Debian. Why not supporting both?

## Detailed Description

When trying to install the `.deb` package in Debian (12, bookworm, kernel 6.1.0-26-amd64), I get the following message, quite similar to [#375 ](https://github.com/openstudiocoalition/OpenStudioApplication/issues/375):
```
$ sudo apt install ./OpenStudioApplication-1.8.0+2722e3e751-Ubuntu24.04.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'openstudioapplication-1.8.0' instead of './OpenStudioApplication-1.8.0+2722e3e751-Ubuntu24.04.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openstudioapplication-1.8.0 : Depends: libwxgtk3.0-0v5 (>= 3.0.0) but it is not installable or
                                        libwxgtk3.0-0 (>= 3.0.0) but it is not installable or
                                        libwxgtk3.0-gtk3-0v5 (>= 3.0.0) but it is not installable or
                                        libwxgtk3.2-1t64 (>= 3.2.0) but it is not installable
```

I know that the openstudiocoalition.org site explicitly says: _OpenStudio Application is supported on 64-bit versions of Windows, OS X, and Ubuntu_. It would be great if Debian was supported as well. Perhaps it is supposed to work in Debian as well. Is it?

**Comment by jmarrec** [comment]
what's the name of the package corresponding to libwxgtk version 3+ in your distro? I guess since this is bookworm it's libwxgtk3.2-1?

https://packages.debian.org/bookworm/libwxgtk3.2-1

**Comment by jmarrec** [comment]
> Ubuntu is a derivative of Debian. Why not supporting both?

Because we have (very) limited resources. For example, I already have to keep a mac M1, a Windows 10 machine, a windows 10 Virtual Machine, a windows 11 VM, an Ubuntu 24.04 machine, an Ubuntu 22.04 VM and an Ubuntu 24.04 VM up to date to keep with the system, dependencies and our own code changes so I can build and test installers (on fresh) and ensure our app is still working fine on all systems we support. It's not like I'm dreaming of needing to add another.

* Anyways, I've opened https://github.com/openstudiocoalition/OpenStudioApplication/pull/765. 

In a few minutes, could you grab the 24.04 .deb that will be posted at https://github.com/openstudiocoalition/OpenStudioApplication/actions/runs/11583075938?pr=765 and try again please?

**Comment by fluxion-t** [comment]
> what's the name of the package corresponding to libwxgtk version 3+ in your distro? I guess since this is bookworm it's libwxgtk3.2-1?

That's correct.

> Anyways, I've opened https://github.com/openstudiocoalition/OpenStudioApplication/pull/765.

Many thanks for that. I could install it without any dependency problem. Had to install libxcb-cursor0 but that was trivial.

Unfortunately, this package requires glibc 2.38, whereas Debian stable is still at glibc 2.36. This is an entirely different problem. 

I fully understand that resources are limited, and I thank you again for that effort. When I opened this issue, I suggested that Debian could be supported _as well_, but I should have said _instead_. Supporting Debian is usually a more stable baseline, as packages built for Debian are more likely to be compatible with Ubuntu than the reverse. This would mean broader compatibility while still covering Ubuntu’s user base. Just a suggestion. In the meantime, I'll try to spin an Ubuntu container.

Thanks.

**Comment by jmarrec** [comment]
@fluxion-t you should probably try the 20.04 or 22.04 deb installer instead. They have an older glibc. I think 20.04 is 2.31 and 22.04 is 2.35

**Comment by fluxion-t** [comment]
> @fluxion-t you should probably try the 20.04 or 22.04 deb installer instead. They have an older glibc. I think 20.04 is 2.31 and 22.04 is 2.35

Installing .deb for 22.04 worked. Didn't realise you committed those changes to the three versions. 

Thank you very, very much.

**Comment by jmarrec** [comment]
Cool, glad it worked. Thanks for testing it out @fluxion-t
