### ISSUE TITLE
Version 2.9.1 not working for some Intel chips

### ISSUE THREAD

**Issue by kiiibl** [openstudiocoalition/OpenStudioApplication#764]
Issue overview
I have a "Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz", and I want to run Openstudio 2.9.1 but it crashes some seconds after starting it. I found a table on another Issue with Intel chips not working for version 2.8.1. Is there any chance there is a table like that for version 2.9.1?

And is there any Information about problems with AMD chips? I have a computer with a "AMD Ryzen 5 4500 U" and it works just fine. So if I buy a new Computer with a AMD chip will it work?

Thanks in advance for your responses and time!
Cheers,
Lucas Glück

**Comment by jmarrec** [comment]
Did you mean to report this to https://github.com/NREL/OpenStudio?

**Comment by kiiibl** [comment]
Yes
No idea why I wrote it here.
