### ISSUE TITLE
Geometry Editor not working on Ubuntu

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#95]
Issue overview
--------------

```
$ /usr/local/openstudioapplication-1.0.0-rc1/bin/OpenStudioApp
[0407/123432.277030:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.0.0-rc1/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
[0407/123432.320588:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 

DevTools listening on ws://127.0.0.1:41993/devtools/browser/f7532e07-6bd4-4ade-b6a4-03e91f8b029c
Critical: THREE.WebGLRenderer: Error creating WebGL context.
Critical: Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null

```

**Note**: `cd /usr/local/openstudioapplication-1.0.0-rc1/bin/ && ./OpenStudioApp` does the same.

## Current Behavior

Doesn't work

## Expected Behavior

Should work

## Steps to Reproduce

1. Load the OSApp
2. Go to the "Geometry Editor" tab

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 18.04
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.0.0-rc1, 0845fd16bb

**Comment by jmarrec** [comment]
Ok, I found it: We are no longer shipping the plugins for Xcbgl. Locally I can make the geoemtry editor working

```
cd /usr/local/openstudioapplication-1.0.0-rc1/bin/
sudo mkdir xcbglintegrations
sudo cp ~/Software/Others/OSApp-build/Qt-install/plugins/xcbglintegrations/libqxcb-glx-integration.so .
```

**Comment by eapuertoc** [comment]
I've installed 1.1.0 version of OpenStudio in Ubuntu 20.14 and pops ups the following error when I use "Geometry" Tab.

0216/193531.747208:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale

Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0/resources. Trying parent directory...

Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0. Trying application directory...

Installed Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/translations/qtwebengine_locales. Trying application directory...

Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.

Path override failed for key ui::DIR_LOCALES and path '/home/eapc/.QtWebEngineProcess'
[0216/193531.768192:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale


DevTools listening on ws://127.0.0.1:39543/devtools/browser/9ccf7c26-5c67-4d58-90ac-fd8459aa3292
Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0/resources. Trying parent directory...

Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0. Trying application directory...

Installed Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/translations/qtwebengine_locales. Trying application directory...

Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.

Path override failed for key ui::DIR_LOCALES and path '/home/$USER/.QtWebEngineProcess'
[0216/193531.830221:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 

I followed the instructions above 

![GeometryError](https://user-images.githubusercontent.com/60450931/108144254-eb488f00-708e-11eb-89e7-a28f0abf60d2.jpg)
but the folder already exits and there is not the content of the second command

**Comment by antoine-galataud** [comment]
same for me, using OpenStudioApp-1.1.0, console traces:

```
[0311/203008.516882:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0/resources. Trying parent directory...
Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0. Trying application directory...
Installed Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[0311/203008.545687:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 

DevTools listening on ws://127.0.0.1:43879/devtools/browser/c046e8af-e6e8-488c-b31e-0fef766fe340
Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0/resources. Trying parent directory...
Qt WebEngine resources not found at /usr/local/openstudioapplication-1.1.0. Trying application directory...
Installed Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/local/openstudioapplication-1.1.0/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[0311/203008.667081:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale
```

Note: I have tested opening same model with OpenStudio 2.9.1, works ok.

**Comment by jmarrec** [comment]
I think we're going to have to add a Github Actions (GHA) runner to build a specific 20.04 installer. (EnergyPlus is doing it, and so is OpenStudio starting in the future 3.2.0 release).

**Comment by ArnaudBvr** [comment]
I checked in `/usr/local/openstudioapplication-1.1.0/bin/xcbglintegrations` and file `libqxcb-glx-integration.so` is present (fresh install). 

Any idea on why the geometry editor is not working ? Any temporary fix while waiting for OSA 1.2.0 ?

**Comment by macumber** [comment]
@jmarrec there already is a `ubuntu-20.04` runner in the matrix, looks like that has been there for a while.  Can you explain what you meant by "add a Github Actions (GHA) runner to build a specific 20.04 installer"?  You think we need to set some CMake configurations differently on 20.04?

**Comment by macumber** [comment]
What versions of Ubuntu are people using?  20.04 is still the current LTS version.

**Comment by MatthewSteen** [comment]
I'm using 20.04 on my personal and work (via WSL2) machines.

**Comment by ArnaudBvr** [comment]
> What versions of Ubuntu are people using? 20.04 is still the current LTS version.

I'm also on 20.04, same as @MatthewSteen

**Comment by jmarrec** [comment]
@macumber Yeah it's definitely added already in terms of runner + FindOpenStudioSDK.cmake now, no further action needed at this point. I've done that when we bumped to 3.2.0-rc1: https://github.com/openstudiocoalition/OpenStudioApplication/pull/329, specifically in this commit: https://github.com/openstudiocoalition/OpenStudioApplication/pull/329/commits/0d032771fcbdb3a24b65e64d5bfbaa0dbd334174

**Comment by jmarrec** [comment]
I'm looking into this issue right now

**Comment by jmarrec** [comment]
Difference, for OpenStudioApplication 1.1.0 official from Ubuntu18.04 (left) to Ubuntu 20.04

Produced with `cd /usr/local/openstudioapplication-1.1.0/bin && OPENSTUDIO_APPLICATION_DEBUG=1 QT_DEBUG_PLUGINS=1 ./OpenStudioApp`

![image](https://user-images.githubusercontent.com/5479063/119497472-e87fc900-bd64-11eb-83d8-276711f3cc2b.png)

**Comment by jmarrec** [comment]
https://bugreports.qt.io/browse/QTBUG-82589

**Comment by ArnaudBvr** [comment]
> https://bugreports.qt.io/browse/QTBUG-82589

I read that and got the gist ; not sure how to fix it though. Is there anything I can do locally as a temporary fix or is it up to you devs to release a fix in the next update ?

**Comment by jmarrec** [comment]
I'm kinda clueless about what's actually happening. I locally made copies of the resources/translations files in the location where the loader expects them, but that doesn't solve the issue whatsoever: the geometry preview view stays completely blank...

**Comment by jmarrec** [comment]
@macumber any thoughts?

I also noticed this weird linker error in the Ubuntu 20.04 build: https://github.com/openstudiocoalition/OpenStudioApplication/runs/2591209238?check_suite_focus=true#step:18:964 . I don't think it's related though.

```
/usr/bin/ld: Qt-install/5.15.0/gcc_64/lib/libQt5WebEngineCore.so.5.15.0: .dynsym local symbol at index 3 (>= sh_info of 3)
/usr/bin/ld: Qt-install/5.15.0/gcc_64/lib/libQt5WebEngineCore.so.5.15.0: .dynsym local symbol at index 4 (>= sh_info of 3)
[...]
```

**Comment by jmarrec** [comment]
Hum, if I replace the geometry_preview.html with a hello world example, then it works...

```
<!DOCTYPE html>
<html>
<head>
<title><%=title%></title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" /i>

</head>
<body>
  HELLO WORLD!
</body>
</html>
```

**Comment by jmarrec** [comment]
See commit https://github.com/openstudiocoalition/OpenStudioApplication/commit/fb2630c194aa84ab3b5500fca427c5fb78d4f30a

Ubuntu 18.04:

```
Debug: Loading started ((null):0, (null))
Debug: Page Loading Started ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  0 ((null):0, (null))
Debug: Page Loading Progress:  0 ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  26 ((null):0, (null))
Debug: Page Loading Progress:  26 ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  100 ((null):0, (null))
Debug: Page Loading Progress:  100 ((null):0, (null))
Debug: onLoadFinished, ok= true , title= "<%=title%>" ((null):0, (null))
Debug: Page Loading Finished:  true ((null):0, (null))
```

**Comment by jmarrec** [comment]
OK some progress. I changed this https://github.com/openstudiocoalition/OpenStudioApplication/blob/e47cbb1e9ca01179fe5547f96100291392902b5f/src/openstudio_lib/GeometryPreviewView.cpp#L125

To load from my local (non-embedded) filesystem:

```
  m_view->load(QUrl("file:///home/julien/Software/Others/OpenStudioApplication/src/openstudio_lib/library/geometry_preview.html"));
```

Now:



```
DevTools listening on ws://127.0.0.1:46495/devtools/browser/430bc5a8-7a41-4eb2-b734-c1d0ff00517d
Warning: Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:46495 ((null):0, (null))
Debug: Loading started ((null):0, (null))
Debug: Page Loading Started ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  0 ((null):0, (null))
Debug: Page Loading Progress:  0 ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  44 ((null):0, (null))
Debug: Page Loading Progress:  44 ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  70 ((null):0, (null))
Debug: Page Loading Progress:  70 ((null):0, (null))
Debug: PreviewWebView::onLoadProgress:  100 ((null):0, (null))
Debug: Page Loading Progress:  100 ((null):0, (null))
Debug: onLoadFinished, ok= true , title= "<%=title%>" ((null):0, (null))
Debug: Page Loading Finished:  true ((null):0, (null))
[55608:55608:0525/181223.662734:INFO:CONSOLE(529)] "THREE.WebGLRenderer 71", source: file:///home/julien/Software/Others/OpenStudioApplication/src/openstudio_lib/library/geometry_preview.html (529)
Critical: THREE.WebGLRenderer: Error creating WebGL context. (file:///home/julien/Software/Others/OpenStudioApplication/src/openstudio_lib/library/geometry_preview.html:8, (null))
[55608:55608:0525/181223.664316:INFO:CONSOLE(8)] "THREE.WebGLRenderer: Error creating WebGL context.", source: file:///home/julien/Software/Others/OpenStudioApplication/src/openstudio_lib/library/geometry_preview.html (8)
Critical: Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null (file:///home/julien/Software/Others/OpenStudioApplication/src/openstudio_lib/library/geometry_preview.html:533, (null))
[55608:55608:0525/181223.668151:INFO:CONSOLE(533)] "Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null", source: file:///home/julien/Software/Others/OpenStudioApplication/src/openstudio_lib/library/geometry_preview.html (533)

```

**Comment by jmarrec** [comment]
I've found a (shitty) workaround, which consists into loading the content of the embedded file, then calling QWebEngineView::setHTML. I've opened a question on stackoverflow here, in the hope of getting pointers: https://stackoverflow.com/questions/67692525/cannot-load-qrc-html-file-in-qwebengineview-on-ubuntu-20-04-only

**Comment by jmarrec** [comment]
@eapuertoc @ArnaudBvr @MatthewSteen Could any of you install the v1.2.0-rc2 I just released and report back please? It should fix it... https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc2

**Comment by eapuertoc** [comment]
Hi, I installed but doesn't open:

./OpenStudioApp: error while loading shared libraries: libopenstudiolib.so: cannot open shared object file: No such file or directory

Something I install wrong?

**Comment by jmarrec** [comment]
@eapuertoc Thanks for testing. I will look into it...

**Comment by jmarrec** [comment]
@eapuertoc Could you try again with https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc2 please? 

I tried on one of my machines and it segfaulted, but I am not sure if it's specific to my system (I did some weird stuff with my system libraries recently...).

@macumber do you have a 20.04 handy?

**Comment by jmarrec** [comment]
Ubuntu 18.04:

```
(py39)julien@Downloads$ /usr/local/openstudioapplication-1.2.0-alpha/bin/OpenStudioApp
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

This is going great!

**Comment by jmarrec** [comment]
Ubuntu 20.04

```
(py39)julien@bin$ diff /usr/local/openstudioapplication-1.1.0/bin/ /usr/local/openstudioapplication-1.2.0-alpha/bin/
Binary files /usr/local/openstudioapplication-1.1.0/bin/install_utility and /usr/local/openstudioapplication-1.2.0-alpha/bin/install_utility differ
Binary files /usr/local/openstudioapplication-1.1.0/bin/libopenstudiolib.so and /usr/local/openstudioapplication-1.2.0-alpha/bin/libopenstudiolib.so differ
Only in /usr/local/openstudioapplication-1.2.0-alpha/bin/: libQt5XcbQpa
Only in /usr/local/openstudioapplication-1.2.0-alpha/bin/: libQt5XcbQpa.so
Only in /usr/local/openstudioapplication-1.1.0/bin/: libQt5XcbQpa.so.5
Only in /usr/local/openstudioapplication-1.1.0/bin/: libQt5XcbQpa.so.5.15
Only in /usr/local/openstudioapplication-1.1.0/bin/: libQt5XcbQpa.so.5.15.0
Binary files /usr/local/openstudioapplication-1.1.0/bin/openstudio and /usr/local/openstudioapplication-1.2.0-alpha/bin/openstudio differ
Binary files /usr/local/openstudioapplication-1.1.0/bin/OpenStudioApp and /usr/local/openstudioapplication-1.2.0-alpha/bin/OpenStudioApp differ
Only in /usr/local/openstudioapplication-1.1.0/bin/: OpenStudioApp-1.1.0
Only in /usr/local/openstudioapplication-1.2.0-alpha/bin/: OpenStudioApp-1.2.0-alpha
Common subdirectories: /usr/local/openstudioapplication-1.1.0/bin/platforms and /usr/local/openstudioapplication-1.2.0-alpha/bin/platforms
Common subdirectories: /usr/local/openstudioapplication-1.1.0/bin/xcbglintegrations and /usr/local/openstudioapplication-1.2.0-alpha/bin/xcbglintegrations
```

**Comment by jmarrec** [comment]
Ok I can fix it manually, it is indeed due to libQt5XcbQpa

```
cd /usr/local/openstudioapplication-1.2.0-alpha/bin/
sudo ln -sf libQt5XcbQpa.so libQt5XcbQpa.so.5
sudo ln -sf libQt5XcbQpa.so libQt5XcbQpa.so.5.15
sudo ln -sf libQt5XcbQpa.so libQt5XcbQpa.so.5.15.0
```

With that, the OpenStudioApp launches...

**Comment by jmarrec** [comment]
I think it's your changed here @macumber https://github.com/openstudiocoalition/OpenStudioApplication/commit/35e36e010366003ce11e7ecd30a4d13b75349bf2#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR570

**Comment by jmarrec** [comment]
with your change, cmake picks up:

```
 QT_QXCBQPA                      */opt/Qt/5.15.0/gcc_64/lib/libQt5XcbQpa.so
```
As a result

```
/_CPack_Packages/Linux/DEB/OpenStudioApplication-1.2.0-alpha+e8f47a7616-Ubuntu20.04/usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so
./_CPack_Packages/Linux/DEB/OpenStudioApplication-1.2.0-alpha+e8f47a7616-Ubuntu20.04/usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa
```

If I revert, cmake picks up:

```
 QT_QXCBQPA                      */opt/Qt/5.15.0/gcc_64/lib/libQt5XcbQpa.so.5.15.0
```

AS a result:

```
./_CPack_Packages/Linux/DEB/OpenStudioApplication-1.2.0-alpha+e8f47a7616-Ubuntu20.04/usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so.5.15.0
./_CPack_Packages/Linux/DEB/OpenStudioApplication-1.2.0-alpha+e8f47a7616-Ubuntu20.04/usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so.5
./_CPack_Packages/Linux/DEB/OpenStudioApplication-1.2.0-alpha+e8f47a7616-Ubuntu20.04/usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so.5.15
```

SO confirmed

**Comment by eapuertoc** [comment]
Hi, I follow the instructions:
cd /usr/local/openstudioapplication-1.2.0-alpha/bin/
sudo ln -sf libQt5XcbQpa.so libQt5XcbQpa.so.5
sudo ln -sf libQt5XcbQpa.so libQt5XcbQpa.so.5.15
sudo ln -sf libQt5XcbQpa.so libQt5XcbQpa.so.5.15.0

Same problem. if I copy the libopenstudiolib.so file i the bin folder it pops up the following error:

./OpenStudioApp: error while loading shared libraries: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory

So I imagine, it will continue with each file same error if is corrected one by one.

**Comment by macumber** [comment]
@eapuertoc did you try the v1.2.0-rc4 release?  There were some changes in the Linux installer that should have helped:

https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc4

**Comment by eapuertoc** [comment]
Hi @macumber, I didn't see that link in the comments. I used and work almost fine, Geometry works perfect, the only little problem is that the maximize button doesn't exists. But it's long enough to work with. Thank you for you help.

**Comment by jmarrec** [comment]
@eapuertoc Could you send a screenshot of the maximize button thing?

**Comment by eapuertoc** [comment]
![ImageOpenstudio](https://user-images.githubusercontent.com/60450931/120217558-22861a80-c1fe-11eb-9b5f-cab931cbd213.jpg)

**Comment by MatthewSteen** [comment]
The Geometry tab (and min/max buttons) works on my copy of [v1.2.0-rc5](https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc5) on 20.04. This is a 3.1.0 OSM opened with 1.2.0-rc5. 

![Screenshot from 2021-05-31 10-35-38](https://user-images.githubusercontent.com/8397034/120221733-24e77500-c1fc-11eb-9271-fee4560b197f.png)

**Comment by eapuertoc** [comment]
I can't specify where's the problem, doesn't generates error when I run in terminal. The first time you open appears, but if you clicked it dissapears.

**Comment by eapuertoc** [comment]
I found something I hope it could help.
I used my other monitor to a project, and find out that when the screen is big (mine is 32"). The maximize button does appears.
